/*
Beyond Networking Service(BNS) Public IP/Security Group API

Public IP/Security Group API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package network

import (
	"encoding/json"
	"fmt"
)

// checks if the BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel{}

// BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel struct for BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel
type BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel struct {
	PublicIp             BnsNetworkV1ApiGetPublicIpModelFloatingIpModel `json:"public_ip"`
	AdditionalProperties map[string]interface{}
}

type _BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel

// NewBnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel instantiates a new BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel(publicIp BnsNetworkV1ApiGetPublicIpModelFloatingIpModel) *BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel {
	this := BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel{}
	this.PublicIp = publicIp
	return &this
}

// NewBnsNetworkV1ApiGetPublicIpModelResponsePublicIpModelWithDefaults instantiates a new BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBnsNetworkV1ApiGetPublicIpModelResponsePublicIpModelWithDefaults() *BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel {
	this := BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel{}
	return &this
}

// GetPublicIp returns the PublicIp field value
func (o *BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel) GetPublicIp() BnsNetworkV1ApiGetPublicIpModelFloatingIpModel {
	if o == nil {
		var ret BnsNetworkV1ApiGetPublicIpModelFloatingIpModel
		return ret
	}

	return o.PublicIp
}

// GetPublicIpOk returns a tuple with the PublicIp field value
// and a boolean to check if the value has been set.
func (o *BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel) GetPublicIpOk() (*BnsNetworkV1ApiGetPublicIpModelFloatingIpModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicIp, true
}

// SetPublicIp sets field value
func (o *BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel) SetPublicIp(v BnsNetworkV1ApiGetPublicIpModelFloatingIpModel) {
	o.PublicIp = v
}

func (o BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["public_ip"] = o.PublicIp

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"public_ip",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel := _BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel{}

	err = json.Unmarshal(data, &varBnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel)

	if err != nil {
		return err
	}

	*o = BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel(varBnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "public_ip")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel struct {
	value *BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel
	isSet bool
}

func (v NullableBnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel) Get() *BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel {
	return v.value
}

func (v *NullableBnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel) Set(val *BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel(val *BnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel) *NullableBnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel {
	return &NullableBnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel{value: val, isSet: true}
}

func (v NullableBnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBnsNetworkV1ApiGetPublicIpModelResponsePublicIpModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
