/*
Beyond Networking Service(BNS) Public IP/Security Group API

Public IP/Security Group API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package network

import (
	"encoding/json"
	"fmt"
)

// checks if the BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel{}

// BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel struct for BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel
type BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel struct {
	SecurityGroup        BnsNetworkV1ApiGetSecurityGroupModelSecurityGroupModel `json:"security_group"`
	AdditionalProperties map[string]interface{}
}

type _BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel

// NewBnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel instantiates a new BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel(securityGroup BnsNetworkV1ApiGetSecurityGroupModelSecurityGroupModel) *BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel {
	this := BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel{}
	this.SecurityGroup = securityGroup
	return &this
}

// NewBnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModelWithDefaults instantiates a new BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModelWithDefaults() *BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel {
	this := BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel{}
	return &this
}

// GetSecurityGroup returns the SecurityGroup field value
func (o *BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel) GetSecurityGroup() BnsNetworkV1ApiGetSecurityGroupModelSecurityGroupModel {
	if o == nil {
		var ret BnsNetworkV1ApiGetSecurityGroupModelSecurityGroupModel
		return ret
	}

	return o.SecurityGroup
}

// GetSecurityGroupOk returns a tuple with the SecurityGroup field value
// and a boolean to check if the value has been set.
func (o *BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel) GetSecurityGroupOk() (*BnsNetworkV1ApiGetSecurityGroupModelSecurityGroupModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecurityGroup, true
}

// SetSecurityGroup sets field value
func (o *BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel) SetSecurityGroup(v BnsNetworkV1ApiGetSecurityGroupModelSecurityGroupModel) {
	o.SecurityGroup = v
}

func (o BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["security_group"] = o.SecurityGroup

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"security_group",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel := _BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel{}

	err = json.Unmarshal(data, &varBnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel)

	if err != nil {
		return err
	}

	*o = BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel(varBnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "security_group")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel struct {
	value *BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel
	isSet bool
}

func (v NullableBnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel) Get() *BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel {
	return v.value
}

func (v *NullableBnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel) Set(val *BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel(val *BnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel) *NullableBnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel {
	return &NullableBnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel{value: val, isSet: true}
}

func (v NullableBnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBnsNetworkV1ApiGetSecurityGroupModelResponseSecurityGroupModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
