/*
Secrets Manager API

Secrets Manager API

API version: 1.3.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package secretsmanager

import (
	"encoding/json"
	"fmt"
)

// checks if the GetSecretVersionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSecretVersionResponse{}

// GetSecretVersionResponse struct for GetSecretVersionResponse
type GetSecretVersionResponse struct {
	// 시크릿 버전 데이터
	Version              GetSecretVersionVersion `json:"version"`
	AdditionalProperties map[string]interface{}
}

type _GetSecretVersionResponse GetSecretVersionResponse

// NewGetSecretVersionResponse instantiates a new GetSecretVersionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSecretVersionResponse(version GetSecretVersionVersion) *GetSecretVersionResponse {
	this := GetSecretVersionResponse{}
	this.Version = version
	return &this
}

// NewGetSecretVersionResponseWithDefaults instantiates a new GetSecretVersionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSecretVersionResponseWithDefaults() *GetSecretVersionResponse {
	this := GetSecretVersionResponse{}
	return &this
}

// GetVersion returns the Version field value
func (o *GetSecretVersionResponse) GetVersion() GetSecretVersionVersion {
	if o == nil {
		var ret GetSecretVersionVersion
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *GetSecretVersionResponse) GetVersionOk() (*GetSecretVersionVersion, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *GetSecretVersionResponse) SetVersion(v GetSecretVersionVersion) {
	o.Version = v
}

func (o GetSecretVersionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSecretVersionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetSecretVersionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSecretVersionResponse := _GetSecretVersionResponse{}

	err = json.Unmarshal(data, &varGetSecretVersionResponse)

	if err != nil {
		return err
	}

	*o = GetSecretVersionResponse(varGetSecretVersionResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetSecretVersionResponse struct {
	value *GetSecretVersionResponse
	isSet bool
}

func (v NullableGetSecretVersionResponse) Get() *GetSecretVersionResponse {
	return v.value
}

func (v *NullableGetSecretVersionResponse) Set(val *GetSecretVersionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSecretVersionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSecretVersionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSecretVersionResponse(val *GetSecretVersionResponse) *NullableGetSecretVersionResponse {
	return &NullableGetSecretVersionResponse{value: val, isSet: true}
}

func (v NullableGetSecretVersionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSecretVersionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
