/*
Secrets Manager API

Secrets Manager API

API version: 1.3.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package secretsmanager

import (
	"encoding/json"
	"fmt"
)

// checks if the AddSecretsAccessTargetsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddSecretsAccessTargetsResponse{}

// AddSecretsAccessTargetsResponse struct for AddSecretsAccessTargetsResponse
type AddSecretsAccessTargetsResponse struct {
	// 접근 제어 허용 대상 목록 또는 처리 결과
	Targets              Bulk `json:"targets"`
	AdditionalProperties map[string]interface{}
}

type _AddSecretsAccessTargetsResponse AddSecretsAccessTargetsResponse

// NewAddSecretsAccessTargetsResponse instantiates a new AddSecretsAccessTargetsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddSecretsAccessTargetsResponse(targets Bulk) *AddSecretsAccessTargetsResponse {
	this := AddSecretsAccessTargetsResponse{}
	this.Targets = targets
	return &this
}

// NewAddSecretsAccessTargetsResponseWithDefaults instantiates a new AddSecretsAccessTargetsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddSecretsAccessTargetsResponseWithDefaults() *AddSecretsAccessTargetsResponse {
	this := AddSecretsAccessTargetsResponse{}
	return &this
}

// GetTargets returns the Targets field value
func (o *AddSecretsAccessTargetsResponse) GetTargets() Bulk {
	if o == nil {
		var ret Bulk
		return ret
	}

	return o.Targets
}

// GetTargetsOk returns a tuple with the Targets field value
// and a boolean to check if the value has been set.
func (o *AddSecretsAccessTargetsResponse) GetTargetsOk() (*Bulk, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Targets, true
}

// SetTargets sets field value
func (o *AddSecretsAccessTargetsResponse) SetTargets(v Bulk) {
	o.Targets = v
}

func (o AddSecretsAccessTargetsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddSecretsAccessTargetsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["targets"] = o.Targets

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AddSecretsAccessTargetsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"targets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddSecretsAccessTargetsResponse := _AddSecretsAccessTargetsResponse{}

	err = json.Unmarshal(data, &varAddSecretsAccessTargetsResponse)

	if err != nil {
		return err
	}

	*o = AddSecretsAccessTargetsResponse(varAddSecretsAccessTargetsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "targets")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAddSecretsAccessTargetsResponse struct {
	value *AddSecretsAccessTargetsResponse
	isSet bool
}

func (v NullableAddSecretsAccessTargetsResponse) Get() *AddSecretsAccessTargetsResponse {
	return v.value
}

func (v *NullableAddSecretsAccessTargetsResponse) Set(val *AddSecretsAccessTargetsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAddSecretsAccessTargetsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAddSecretsAccessTargetsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddSecretsAccessTargetsResponse(val *AddSecretsAccessTargetsResponse) *NullableAddSecretsAccessTargetsResponse {
	return &NullableAddSecretsAccessTargetsResponse{value: val, isSet: true}
}

func (v NullableAddSecretsAccessTargetsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddSecretsAccessTargetsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
