/*
Beyond Networking Service(BNS) VPC API

Testing VPCAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package vpc

import (
	"context"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_vpc_VPCAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test VPCAPIService CreateVpc", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.VPCAPI.CreateVpc(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VPCAPIService DeleteVpc", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var vpcId string

		httpRes, err := apiClient.VPCAPI.DeleteVpc(context.Background(), vpcId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VPCAPIService GetVpc", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var vpcId string

		resp, httpRes, err := apiClient.VPCAPI.GetVpc(context.Background(), vpcId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VPCAPIService ListVpcs", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.VPCAPI.ListVpcs(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VPCAPIService PutBnsVpc", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var vpcId string

		resp, httpRes, err := apiClient.VPCAPI.PutBnsVpc(context.Background(), vpcId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
