/*
kubernetes-engine API

kubernetes-engine API

API version: 1.3.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kubernetesengine

import (
	"encoding/json"
	"fmt"
)

// checks if the VpcInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VpcInfo{}

// VpcInfo struct for VpcInfo
type VpcInfo struct {
	// VPC의 고유 ID
	Id string `json:"id"`
	// 서브넷 정보 목록
	Subnets              []Subnet `json:"subnets"`
	AdditionalProperties map[string]interface{}
}

type _VpcInfo VpcInfo

// NewVpcInfo instantiates a new VpcInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVpcInfo(id string, subnets []Subnet) *VpcInfo {
	this := VpcInfo{}
	this.Id = id
	this.Subnets = subnets
	return &this
}

// NewVpcInfoWithDefaults instantiates a new VpcInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVpcInfoWithDefaults() *VpcInfo {
	this := VpcInfo{}
	return &this
}

// GetId returns the Id field value
func (o *VpcInfo) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *VpcInfo) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *VpcInfo) SetId(v string) {
	o.Id = v
}

// GetSubnets returns the Subnets field value
func (o *VpcInfo) GetSubnets() []Subnet {
	if o == nil {
		var ret []Subnet
		return ret
	}

	return o.Subnets
}

// GetSubnetsOk returns a tuple with the Subnets field value
// and a boolean to check if the value has been set.
func (o *VpcInfo) GetSubnetsOk() ([]Subnet, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subnets, true
}

// SetSubnets sets field value
func (o *VpcInfo) SetSubnets(v []Subnet) {
	o.Subnets = v
}

func (o VpcInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VpcInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["subnets"] = o.Subnets

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VpcInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"subnets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVpcInfo := _VpcInfo{}

	err = json.Unmarshal(data, &varVpcInfo)

	if err != nil {
		return err
	}

	*o = VpcInfo(varVpcInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "subnets")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVpcInfo struct {
	value *VpcInfo
	isSet bool
}

func (v NullableVpcInfo) Get() *VpcInfo {
	return v.value
}

func (v *NullableVpcInfo) Set(val *VpcInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableVpcInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableVpcInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpcInfo(val *VpcInfo) *NullableVpcInfo {
	return &NullableVpcInfo{value: val, isSet: true}
}

func (v NullableVpcInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpcInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
