/*
kubernetes-engine API

kubernetes-engine API

API version: 1.3.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kubernetesengine

import (
	"encoding/json"
	"fmt"
)

// checks if the OMTInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OMTInfo{}

// OMTInfo struct for OMTInfo
type OMTInfo struct {
	// 해당 버전의 사용 중단 여부
	IsDeprecated bool `json:"is_deprecated"`
	// 지원 종료 시점(ISO 8601 형식, UTC)
	Eol string `json:"eol"`
	// Kubernetes 마이너 버전
	MinorVersion string `json:"minor_version"`
	// 업그레이드 가능한 다음 버전
	NextVersion string `json:"next_version"`
	// Kubernetes 패치 버전
	PatchVersion         string `json:"patch_version"`
	AdditionalProperties map[string]interface{}
}

type _OMTInfo OMTInfo

// NewOMTInfo instantiates a new OMTInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOMTInfo(isDeprecated bool, eol string, minorVersion string, nextVersion string, patchVersion string) *OMTInfo {
	this := OMTInfo{}
	this.IsDeprecated = isDeprecated
	this.Eol = eol
	this.MinorVersion = minorVersion
	this.NextVersion = nextVersion
	this.PatchVersion = patchVersion
	return &this
}

// NewOMTInfoWithDefaults instantiates a new OMTInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOMTInfoWithDefaults() *OMTInfo {
	this := OMTInfo{}
	return &this
}

// GetIsDeprecated returns the IsDeprecated field value
func (o *OMTInfo) GetIsDeprecated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDeprecated
}

// GetIsDeprecatedOk returns a tuple with the IsDeprecated field value
// and a boolean to check if the value has been set.
func (o *OMTInfo) GetIsDeprecatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsDeprecated, true
}

// SetIsDeprecated sets field value
func (o *OMTInfo) SetIsDeprecated(v bool) {
	o.IsDeprecated = v
}

// GetEol returns the Eol field value
func (o *OMTInfo) GetEol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Eol
}

// GetEolOk returns a tuple with the Eol field value
// and a boolean to check if the value has been set.
func (o *OMTInfo) GetEolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Eol, true
}

// SetEol sets field value
func (o *OMTInfo) SetEol(v string) {
	o.Eol = v
}

// GetMinorVersion returns the MinorVersion field value
func (o *OMTInfo) GetMinorVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MinorVersion
}

// GetMinorVersionOk returns a tuple with the MinorVersion field value
// and a boolean to check if the value has been set.
func (o *OMTInfo) GetMinorVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinorVersion, true
}

// SetMinorVersion sets field value
func (o *OMTInfo) SetMinorVersion(v string) {
	o.MinorVersion = v
}

// GetNextVersion returns the NextVersion field value
func (o *OMTInfo) GetNextVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextVersion
}

// GetNextVersionOk returns a tuple with the NextVersion field value
// and a boolean to check if the value has been set.
func (o *OMTInfo) GetNextVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextVersion, true
}

// SetNextVersion sets field value
func (o *OMTInfo) SetNextVersion(v string) {
	o.NextVersion = v
}

// GetPatchVersion returns the PatchVersion field value
func (o *OMTInfo) GetPatchVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PatchVersion
}

// GetPatchVersionOk returns a tuple with the PatchVersion field value
// and a boolean to check if the value has been set.
func (o *OMTInfo) GetPatchVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PatchVersion, true
}

// SetPatchVersion sets field value
func (o *OMTInfo) SetPatchVersion(v string) {
	o.PatchVersion = v
}

func (o OMTInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OMTInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["is_deprecated"] = o.IsDeprecated
	toSerialize["eol"] = o.Eol
	toSerialize["minor_version"] = o.MinorVersion
	toSerialize["next_version"] = o.NextVersion
	toSerialize["patch_version"] = o.PatchVersion

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OMTInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"is_deprecated",
		"eol",
		"minor_version",
		"next_version",
		"patch_version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOMTInfo := _OMTInfo{}

	err = json.Unmarshal(data, &varOMTInfo)

	if err != nil {
		return err
	}

	*o = OMTInfo(varOMTInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "is_deprecated")
		delete(additionalProperties, "eol")
		delete(additionalProperties, "minor_version")
		delete(additionalProperties, "next_version")
		delete(additionalProperties, "patch_version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOMTInfo struct {
	value *OMTInfo
	isSet bool
}

func (v NullableOMTInfo) Get() *OMTInfo {
	return v.value
}

func (v *NullableOMTInfo) Set(val *OMTInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableOMTInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableOMTInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOMTInfo(val *OMTInfo) *NullableOMTInfo {
	return &NullableOMTInfo{value: val, isSet: true}
}

func (v NullableOMTInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOMTInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
