/*
bns-tgw API

bns-tgw API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tgw

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel{}

// BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel struct for BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel
type BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel struct {
	// Attachment ID
	Id                 string                        `json:"id"`
	ProvisioningStatus NullableTGWProvisioningStatus `json:"provisioning_status,omitempty"`
	ProjectId          NullableString                `json:"project_id,omitempty"`
	ProjectName        NullableString                `json:"project_name,omitempty"`
	ResourceType       NullableResourceType          `json:"resource_type,omitempty"`
	ResourceId         NullableString                `json:"resource_id,omitempty"`
	ResourceName       NullableString                `json:"resource_name,omitempty"`
	ResourceCidrBlock  NullableString                `json:"resource_cidr_block,omitempty"`
	// 연결된 Transit Gateway 정보
	Tgw                  TrasitGatewayResponseModel                                      `json:"tgw"`
	Resources            []BnsTgwV1ApiGetTgwAttachmentModelResourceResponseModel         `json:"resources,omitempty"`
	RouteTable           NullableBnsTgwV1ApiGetTgwAttachmentModelRouteTableResponseModel `json:"route_table,omitempty"`
	CreatedAt            NullableTime                                                    `json:"created_at,omitempty"`
	UpdatedAt            NullableTime                                                    `json:"updated_at,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel

// NewBnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel instantiates a new BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel(id string, tgw TrasitGatewayResponseModel) *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel {
	this := BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel{}
	this.Id = id
	this.Tgw = tgw
	return &this
}

// NewBnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModelWithDefaults instantiates a new BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModelWithDefaults() *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel {
	this := BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel{}
	return &this
}

// GetId returns the Id field value
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetId(v string) {
	o.Id = v
}

// GetProvisioningStatus returns the ProvisioningStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetProvisioningStatus() TGWProvisioningStatus {
	if o == nil || IsNil(o.ProvisioningStatus.Get()) {
		var ret TGWProvisioningStatus
		return ret
	}
	return *o.ProvisioningStatus.Get()
}

// GetProvisioningStatusOk returns a tuple with the ProvisioningStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetProvisioningStatusOk() (*TGWProvisioningStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProvisioningStatus.Get(), o.ProvisioningStatus.IsSet()
}

// HasProvisioningStatus returns a boolean if a field has been set.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) HasProvisioningStatus() bool {
	if o != nil && o.ProvisioningStatus.IsSet() {
		return true
	}

	return false
}

// SetProvisioningStatus gets a reference to the given NullableTGWProvisioningStatus and assigns it to the ProvisioningStatus field.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetProvisioningStatus(v TGWProvisioningStatus) {
	o.ProvisioningStatus.Set(&v)
}

// SetProvisioningStatusNil sets the value for ProvisioningStatus to be an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetProvisioningStatusNil() {
	o.ProvisioningStatus.Set(nil)
}

// UnsetProvisioningStatus ensures that no value is present for ProvisioningStatus, not even an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) UnsetProvisioningStatus() {
	o.ProvisioningStatus.Unset()
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId.Get()) {
		var ret string
		return ret
	}
	return *o.ProjectId.Get()
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectId.Get(), o.ProjectId.IsSet()
}

// HasProjectId returns a boolean if a field has been set.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) HasProjectId() bool {
	if o != nil && o.ProjectId.IsSet() {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given NullableString and assigns it to the ProjectId field.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetProjectId(v string) {
	o.ProjectId.Set(&v)
}

// SetProjectIdNil sets the value for ProjectId to be an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetProjectIdNil() {
	o.ProjectId.Set(nil)
}

// UnsetProjectId ensures that no value is present for ProjectId, not even an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) UnsetProjectId() {
	o.ProjectId.Unset()
}

// GetProjectName returns the ProjectName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetProjectName() string {
	if o == nil || IsNil(o.ProjectName.Get()) {
		var ret string
		return ret
	}
	return *o.ProjectName.Get()
}

// GetProjectNameOk returns a tuple with the ProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectName.Get(), o.ProjectName.IsSet()
}

// HasProjectName returns a boolean if a field has been set.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) HasProjectName() bool {
	if o != nil && o.ProjectName.IsSet() {
		return true
	}

	return false
}

// SetProjectName gets a reference to the given NullableString and assigns it to the ProjectName field.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetProjectName(v string) {
	o.ProjectName.Set(&v)
}

// SetProjectNameNil sets the value for ProjectName to be an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetProjectNameNil() {
	o.ProjectName.Set(nil)
}

// UnsetProjectName ensures that no value is present for ProjectName, not even an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) UnsetProjectName() {
	o.ProjectName.Unset()
}

// GetResourceType returns the ResourceType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetResourceType() ResourceType {
	if o == nil || IsNil(o.ResourceType.Get()) {
		var ret ResourceType
		return ret
	}
	return *o.ResourceType.Get()
}

// GetResourceTypeOk returns a tuple with the ResourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetResourceTypeOk() (*ResourceType, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourceType.Get(), o.ResourceType.IsSet()
}

// HasResourceType returns a boolean if a field has been set.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) HasResourceType() bool {
	if o != nil && o.ResourceType.IsSet() {
		return true
	}

	return false
}

// SetResourceType gets a reference to the given NullableResourceType and assigns it to the ResourceType field.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetResourceType(v ResourceType) {
	o.ResourceType.Set(&v)
}

// SetResourceTypeNil sets the value for ResourceType to be an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetResourceTypeNil() {
	o.ResourceType.Set(nil)
}

// UnsetResourceType ensures that no value is present for ResourceType, not even an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) UnsetResourceType() {
	o.ResourceType.Unset()
}

// GetResourceId returns the ResourceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetResourceId() string {
	if o == nil || IsNil(o.ResourceId.Get()) {
		var ret string
		return ret
	}
	return *o.ResourceId.Get()
}

// GetResourceIdOk returns a tuple with the ResourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourceId.Get(), o.ResourceId.IsSet()
}

// HasResourceId returns a boolean if a field has been set.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) HasResourceId() bool {
	if o != nil && o.ResourceId.IsSet() {
		return true
	}

	return false
}

// SetResourceId gets a reference to the given NullableString and assigns it to the ResourceId field.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetResourceId(v string) {
	o.ResourceId.Set(&v)
}

// SetResourceIdNil sets the value for ResourceId to be an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetResourceIdNil() {
	o.ResourceId.Set(nil)
}

// UnsetResourceId ensures that no value is present for ResourceId, not even an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) UnsetResourceId() {
	o.ResourceId.Unset()
}

// GetResourceName returns the ResourceName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetResourceName() string {
	if o == nil || IsNil(o.ResourceName.Get()) {
		var ret string
		return ret
	}
	return *o.ResourceName.Get()
}

// GetResourceNameOk returns a tuple with the ResourceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetResourceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourceName.Get(), o.ResourceName.IsSet()
}

// HasResourceName returns a boolean if a field has been set.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) HasResourceName() bool {
	if o != nil && o.ResourceName.IsSet() {
		return true
	}

	return false
}

// SetResourceName gets a reference to the given NullableString and assigns it to the ResourceName field.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetResourceName(v string) {
	o.ResourceName.Set(&v)
}

// SetResourceNameNil sets the value for ResourceName to be an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetResourceNameNil() {
	o.ResourceName.Set(nil)
}

// UnsetResourceName ensures that no value is present for ResourceName, not even an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) UnsetResourceName() {
	o.ResourceName.Unset()
}

// GetResourceCidrBlock returns the ResourceCidrBlock field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetResourceCidrBlock() string {
	if o == nil || IsNil(o.ResourceCidrBlock.Get()) {
		var ret string
		return ret
	}
	return *o.ResourceCidrBlock.Get()
}

// GetResourceCidrBlockOk returns a tuple with the ResourceCidrBlock field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetResourceCidrBlockOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourceCidrBlock.Get(), o.ResourceCidrBlock.IsSet()
}

// HasResourceCidrBlock returns a boolean if a field has been set.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) HasResourceCidrBlock() bool {
	if o != nil && o.ResourceCidrBlock.IsSet() {
		return true
	}

	return false
}

// SetResourceCidrBlock gets a reference to the given NullableString and assigns it to the ResourceCidrBlock field.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetResourceCidrBlock(v string) {
	o.ResourceCidrBlock.Set(&v)
}

// SetResourceCidrBlockNil sets the value for ResourceCidrBlock to be an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetResourceCidrBlockNil() {
	o.ResourceCidrBlock.Set(nil)
}

// UnsetResourceCidrBlock ensures that no value is present for ResourceCidrBlock, not even an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) UnsetResourceCidrBlock() {
	o.ResourceCidrBlock.Unset()
}

// GetTgw returns the Tgw field value
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetTgw() TrasitGatewayResponseModel {
	if o == nil {
		var ret TrasitGatewayResponseModel
		return ret
	}

	return o.Tgw
}

// GetTgwOk returns a tuple with the Tgw field value
// and a boolean to check if the value has been set.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetTgwOk() (*TrasitGatewayResponseModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tgw, true
}

// SetTgw sets field value
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetTgw(v TrasitGatewayResponseModel) {
	o.Tgw = v
}

// GetResources returns the Resources field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetResources() []BnsTgwV1ApiGetTgwAttachmentModelResourceResponseModel {
	if o == nil {
		var ret []BnsTgwV1ApiGetTgwAttachmentModelResourceResponseModel
		return ret
	}
	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetResourcesOk() ([]BnsTgwV1ApiGetTgwAttachmentModelResourceResponseModel, bool) {
	if o == nil || IsNil(o.Resources) {
		return nil, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given []BnsTgwV1ApiGetTgwAttachmentModelResourceResponseModel and assigns it to the Resources field.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetResources(v []BnsTgwV1ApiGetTgwAttachmentModelResourceResponseModel) {
	o.Resources = v
}

// GetRouteTable returns the RouteTable field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetRouteTable() BnsTgwV1ApiGetTgwAttachmentModelRouteTableResponseModel {
	if o == nil || IsNil(o.RouteTable.Get()) {
		var ret BnsTgwV1ApiGetTgwAttachmentModelRouteTableResponseModel
		return ret
	}
	return *o.RouteTable.Get()
}

// GetRouteTableOk returns a tuple with the RouteTable field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetRouteTableOk() (*BnsTgwV1ApiGetTgwAttachmentModelRouteTableResponseModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.RouteTable.Get(), o.RouteTable.IsSet()
}

// HasRouteTable returns a boolean if a field has been set.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) HasRouteTable() bool {
	if o != nil && o.RouteTable.IsSet() {
		return true
	}

	return false
}

// SetRouteTable gets a reference to the given NullableBnsTgwV1ApiGetTgwAttachmentModelRouteTableResponseModel and assigns it to the RouteTable field.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetRouteTable(v BnsTgwV1ApiGetTgwAttachmentModelRouteTableResponseModel) {
	o.RouteTable.Set(&v)
}

// SetRouteTableNil sets the value for RouteTable to be an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetRouteTableNil() {
	o.RouteTable.Set(nil)
}

// UnsetRouteTable ensures that no value is present for RouteTable, not even an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) UnsetRouteTable() {
	o.RouteTable.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableTime and assigns it to the CreatedAt field.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetCreatedAt(v time.Time) {
	o.CreatedAt.Set(&v)
}

// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}

// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

func (o BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if o.ProvisioningStatus.IsSet() {
		toSerialize["provisioning_status"] = o.ProvisioningStatus.Get()
	}
	if o.ProjectId.IsSet() {
		toSerialize["project_id"] = o.ProjectId.Get()
	}
	if o.ProjectName.IsSet() {
		toSerialize["project_name"] = o.ProjectName.Get()
	}
	if o.ResourceType.IsSet() {
		toSerialize["resource_type"] = o.ResourceType.Get()
	}
	if o.ResourceId.IsSet() {
		toSerialize["resource_id"] = o.ResourceId.Get()
	}
	if o.ResourceName.IsSet() {
		toSerialize["resource_name"] = o.ResourceName.Get()
	}
	if o.ResourceCidrBlock.IsSet() {
		toSerialize["resource_cidr_block"] = o.ResourceCidrBlock.Get()
	}
	toSerialize["tgw"] = o.Tgw
	if o.Resources != nil {
		toSerialize["resources"] = o.Resources
	}
	if o.RouteTable.IsSet() {
		toSerialize["route_table"] = o.RouteTable.Get()
	}
	if o.CreatedAt.IsSet() {
		toSerialize["created_at"] = o.CreatedAt.Get()
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updated_at"] = o.UpdatedAt.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"tgw",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel := _BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel{}

	err = json.Unmarshal(data, &varBnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel)

	if err != nil {
		return err
	}

	*o = BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel(varBnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "provisioning_status")
		delete(additionalProperties, "project_id")
		delete(additionalProperties, "project_name")
		delete(additionalProperties, "resource_type")
		delete(additionalProperties, "resource_id")
		delete(additionalProperties, "resource_name")
		delete(additionalProperties, "resource_cidr_block")
		delete(additionalProperties, "tgw")
		delete(additionalProperties, "resources")
		delete(additionalProperties, "route_table")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel struct {
	value *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel
	isSet bool
}

func (v NullableBnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) Get() *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel {
	return v.value
}

func (v *NullableBnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) Set(val *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel(val *BnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) *NullableBnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel {
	return &NullableBnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel{value: val, isSet: true}
}

func (v NullableBnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBnsTgwV1ApiGetTgwAttachmentModelTgwAttachmentResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
