/*
bns-tgw API

bns-tgw API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tgw

import (
	"encoding/json"
	"time"
)

// checks if the BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel{}

// BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel struct for BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel
type BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel struct {
	Id                   NullableString                                               `json:"id,omitempty"`
	Name                 NullableString                                               `json:"name,omitempty"`
	Region               NullableRegion                                               `json:"region,omitempty"`
	IsShared             NullableBool                                                 `json:"is_shared,omitempty"`
	Attachments          []BnsTgwV1ApiListTransitGatewaysModelAttachmentResponseModel `json:"attachments,omitempty"`
	Options              NullableOptionResponseModel                                  `json:"options,omitempty"`
	ProvisioningStatus   NullableTGWProvisioningStatus                                `json:"provisioning_status,omitempty"`
	ProjectId            NullableString                                               `json:"project_id,omitempty"`
	ProjectName          NullableString                                               `json:"project_name,omitempty"`
	OwnerProjectId       NullableString                                               `json:"owner_project_id,omitempty"`
	OwnerProjectName     NullableString                                               `json:"owner_project_name,omitempty"`
	RouteTables          []BnsTgwV1ApiListTransitGatewaysModelRouteTableResponseModel `json:"route_tables,omitempty"`
	CreatedAt            NullableTime                                                 `json:"created_at,omitempty"`
	UpdatedAt            NullableTime                                                 `json:"updated_at,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel

// NewBnsTgwV1ApiListTransitGatewaysModelTgwResponseModel instantiates a new BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBnsTgwV1ApiListTransitGatewaysModelTgwResponseModel() *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel {
	this := BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel{}
	return &this
}

// NewBnsTgwV1ApiListTransitGatewaysModelTgwResponseModelWithDefaults instantiates a new BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBnsTgwV1ApiListTransitGatewaysModelTgwResponseModelWithDefaults() *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel {
	this := BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetId(v string) {
	o.Id.Set(&v)
}

// SetIdNil sets the value for Id to be an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) UnsetId() {
	o.Id.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) UnsetName() {
	o.Name.Unset()
}

// GetRegion returns the Region field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetRegion() Region {
	if o == nil || IsNil(o.Region.Get()) {
		var ret Region
		return ret
	}
	return *o.Region.Get()
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetRegionOk() (*Region, bool) {
	if o == nil {
		return nil, false
	}
	return o.Region.Get(), o.Region.IsSet()
}

// HasRegion returns a boolean if a field has been set.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) HasRegion() bool {
	if o != nil && o.Region.IsSet() {
		return true
	}

	return false
}

// SetRegion gets a reference to the given NullableRegion and assigns it to the Region field.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetRegion(v Region) {
	o.Region.Set(&v)
}

// SetRegionNil sets the value for Region to be an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetRegionNil() {
	o.Region.Set(nil)
}

// UnsetRegion ensures that no value is present for Region, not even an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) UnsetRegion() {
	o.Region.Unset()
}

// GetIsShared returns the IsShared field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetIsShared() bool {
	if o == nil || IsNil(o.IsShared.Get()) {
		var ret bool
		return ret
	}
	return *o.IsShared.Get()
}

// GetIsSharedOk returns a tuple with the IsShared field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetIsSharedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsShared.Get(), o.IsShared.IsSet()
}

// HasIsShared returns a boolean if a field has been set.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) HasIsShared() bool {
	if o != nil && o.IsShared.IsSet() {
		return true
	}

	return false
}

// SetIsShared gets a reference to the given NullableBool and assigns it to the IsShared field.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetIsShared(v bool) {
	o.IsShared.Set(&v)
}

// SetIsSharedNil sets the value for IsShared to be an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetIsSharedNil() {
	o.IsShared.Set(nil)
}

// UnsetIsShared ensures that no value is present for IsShared, not even an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) UnsetIsShared() {
	o.IsShared.Unset()
}

// GetAttachments returns the Attachments field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetAttachments() []BnsTgwV1ApiListTransitGatewaysModelAttachmentResponseModel {
	if o == nil {
		var ret []BnsTgwV1ApiListTransitGatewaysModelAttachmentResponseModel
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetAttachmentsOk() ([]BnsTgwV1ApiListTransitGatewaysModelAttachmentResponseModel, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []BnsTgwV1ApiListTransitGatewaysModelAttachmentResponseModel and assigns it to the Attachments field.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetAttachments(v []BnsTgwV1ApiListTransitGatewaysModelAttachmentResponseModel) {
	o.Attachments = v
}

// GetOptions returns the Options field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetOptions() OptionResponseModel {
	if o == nil || IsNil(o.Options.Get()) {
		var ret OptionResponseModel
		return ret
	}
	return *o.Options.Get()
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetOptionsOk() (*OptionResponseModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Options.Get(), o.Options.IsSet()
}

// HasOptions returns a boolean if a field has been set.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) HasOptions() bool {
	if o != nil && o.Options.IsSet() {
		return true
	}

	return false
}

// SetOptions gets a reference to the given NullableOptionResponseModel and assigns it to the Options field.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetOptions(v OptionResponseModel) {
	o.Options.Set(&v)
}

// SetOptionsNil sets the value for Options to be an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetOptionsNil() {
	o.Options.Set(nil)
}

// UnsetOptions ensures that no value is present for Options, not even an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) UnsetOptions() {
	o.Options.Unset()
}

// GetProvisioningStatus returns the ProvisioningStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetProvisioningStatus() TGWProvisioningStatus {
	if o == nil || IsNil(o.ProvisioningStatus.Get()) {
		var ret TGWProvisioningStatus
		return ret
	}
	return *o.ProvisioningStatus.Get()
}

// GetProvisioningStatusOk returns a tuple with the ProvisioningStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetProvisioningStatusOk() (*TGWProvisioningStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProvisioningStatus.Get(), o.ProvisioningStatus.IsSet()
}

// HasProvisioningStatus returns a boolean if a field has been set.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) HasProvisioningStatus() bool {
	if o != nil && o.ProvisioningStatus.IsSet() {
		return true
	}

	return false
}

// SetProvisioningStatus gets a reference to the given NullableTGWProvisioningStatus and assigns it to the ProvisioningStatus field.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetProvisioningStatus(v TGWProvisioningStatus) {
	o.ProvisioningStatus.Set(&v)
}

// SetProvisioningStatusNil sets the value for ProvisioningStatus to be an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetProvisioningStatusNil() {
	o.ProvisioningStatus.Set(nil)
}

// UnsetProvisioningStatus ensures that no value is present for ProvisioningStatus, not even an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) UnsetProvisioningStatus() {
	o.ProvisioningStatus.Unset()
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId.Get()) {
		var ret string
		return ret
	}
	return *o.ProjectId.Get()
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectId.Get(), o.ProjectId.IsSet()
}

// HasProjectId returns a boolean if a field has been set.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) HasProjectId() bool {
	if o != nil && o.ProjectId.IsSet() {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given NullableString and assigns it to the ProjectId field.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetProjectId(v string) {
	o.ProjectId.Set(&v)
}

// SetProjectIdNil sets the value for ProjectId to be an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetProjectIdNil() {
	o.ProjectId.Set(nil)
}

// UnsetProjectId ensures that no value is present for ProjectId, not even an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) UnsetProjectId() {
	o.ProjectId.Unset()
}

// GetProjectName returns the ProjectName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetProjectName() string {
	if o == nil || IsNil(o.ProjectName.Get()) {
		var ret string
		return ret
	}
	return *o.ProjectName.Get()
}

// GetProjectNameOk returns a tuple with the ProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectName.Get(), o.ProjectName.IsSet()
}

// HasProjectName returns a boolean if a field has been set.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) HasProjectName() bool {
	if o != nil && o.ProjectName.IsSet() {
		return true
	}

	return false
}

// SetProjectName gets a reference to the given NullableString and assigns it to the ProjectName field.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetProjectName(v string) {
	o.ProjectName.Set(&v)
}

// SetProjectNameNil sets the value for ProjectName to be an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetProjectNameNil() {
	o.ProjectName.Set(nil)
}

// UnsetProjectName ensures that no value is present for ProjectName, not even an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) UnsetProjectName() {
	o.ProjectName.Unset()
}

// GetOwnerProjectId returns the OwnerProjectId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetOwnerProjectId() string {
	if o == nil || IsNil(o.OwnerProjectId.Get()) {
		var ret string
		return ret
	}
	return *o.OwnerProjectId.Get()
}

// GetOwnerProjectIdOk returns a tuple with the OwnerProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetOwnerProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OwnerProjectId.Get(), o.OwnerProjectId.IsSet()
}

// HasOwnerProjectId returns a boolean if a field has been set.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) HasOwnerProjectId() bool {
	if o != nil && o.OwnerProjectId.IsSet() {
		return true
	}

	return false
}

// SetOwnerProjectId gets a reference to the given NullableString and assigns it to the OwnerProjectId field.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetOwnerProjectId(v string) {
	o.OwnerProjectId.Set(&v)
}

// SetOwnerProjectIdNil sets the value for OwnerProjectId to be an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetOwnerProjectIdNil() {
	o.OwnerProjectId.Set(nil)
}

// UnsetOwnerProjectId ensures that no value is present for OwnerProjectId, not even an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) UnsetOwnerProjectId() {
	o.OwnerProjectId.Unset()
}

// GetOwnerProjectName returns the OwnerProjectName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetOwnerProjectName() string {
	if o == nil || IsNil(o.OwnerProjectName.Get()) {
		var ret string
		return ret
	}
	return *o.OwnerProjectName.Get()
}

// GetOwnerProjectNameOk returns a tuple with the OwnerProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetOwnerProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OwnerProjectName.Get(), o.OwnerProjectName.IsSet()
}

// HasOwnerProjectName returns a boolean if a field has been set.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) HasOwnerProjectName() bool {
	if o != nil && o.OwnerProjectName.IsSet() {
		return true
	}

	return false
}

// SetOwnerProjectName gets a reference to the given NullableString and assigns it to the OwnerProjectName field.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetOwnerProjectName(v string) {
	o.OwnerProjectName.Set(&v)
}

// SetOwnerProjectNameNil sets the value for OwnerProjectName to be an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetOwnerProjectNameNil() {
	o.OwnerProjectName.Set(nil)
}

// UnsetOwnerProjectName ensures that no value is present for OwnerProjectName, not even an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) UnsetOwnerProjectName() {
	o.OwnerProjectName.Unset()
}

// GetRouteTables returns the RouteTables field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetRouteTables() []BnsTgwV1ApiListTransitGatewaysModelRouteTableResponseModel {
	if o == nil {
		var ret []BnsTgwV1ApiListTransitGatewaysModelRouteTableResponseModel
		return ret
	}
	return o.RouteTables
}

// GetRouteTablesOk returns a tuple with the RouteTables field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetRouteTablesOk() ([]BnsTgwV1ApiListTransitGatewaysModelRouteTableResponseModel, bool) {
	if o == nil || IsNil(o.RouteTables) {
		return nil, false
	}
	return o.RouteTables, true
}

// HasRouteTables returns a boolean if a field has been set.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) HasRouteTables() bool {
	if o != nil && !IsNil(o.RouteTables) {
		return true
	}

	return false
}

// SetRouteTables gets a reference to the given []BnsTgwV1ApiListTransitGatewaysModelRouteTableResponseModel and assigns it to the RouteTables field.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetRouteTables(v []BnsTgwV1ApiListTransitGatewaysModelRouteTableResponseModel) {
	o.RouteTables = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableTime and assigns it to the CreatedAt field.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetCreatedAt(v time.Time) {
	o.CreatedAt.Set(&v)
}

// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}

// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

func (o BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Region.IsSet() {
		toSerialize["region"] = o.Region.Get()
	}
	if o.IsShared.IsSet() {
		toSerialize["is_shared"] = o.IsShared.Get()
	}
	if o.Attachments != nil {
		toSerialize["attachments"] = o.Attachments
	}
	if o.Options.IsSet() {
		toSerialize["options"] = o.Options.Get()
	}
	if o.ProvisioningStatus.IsSet() {
		toSerialize["provisioning_status"] = o.ProvisioningStatus.Get()
	}
	if o.ProjectId.IsSet() {
		toSerialize["project_id"] = o.ProjectId.Get()
	}
	if o.ProjectName.IsSet() {
		toSerialize["project_name"] = o.ProjectName.Get()
	}
	if o.OwnerProjectId.IsSet() {
		toSerialize["owner_project_id"] = o.OwnerProjectId.Get()
	}
	if o.OwnerProjectName.IsSet() {
		toSerialize["owner_project_name"] = o.OwnerProjectName.Get()
	}
	if o.RouteTables != nil {
		toSerialize["route_tables"] = o.RouteTables
	}
	if o.CreatedAt.IsSet() {
		toSerialize["created_at"] = o.CreatedAt.Get()
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updated_at"] = o.UpdatedAt.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) UnmarshalJSON(data []byte) (err error) {
	varBnsTgwV1ApiListTransitGatewaysModelTgwResponseModel := _BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel{}

	err = json.Unmarshal(data, &varBnsTgwV1ApiListTransitGatewaysModelTgwResponseModel)

	if err != nil {
		return err
	}

	*o = BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel(varBnsTgwV1ApiListTransitGatewaysModelTgwResponseModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "region")
		delete(additionalProperties, "is_shared")
		delete(additionalProperties, "attachments")
		delete(additionalProperties, "options")
		delete(additionalProperties, "provisioning_status")
		delete(additionalProperties, "project_id")
		delete(additionalProperties, "project_name")
		delete(additionalProperties, "owner_project_id")
		delete(additionalProperties, "owner_project_name")
		delete(additionalProperties, "route_tables")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBnsTgwV1ApiListTransitGatewaysModelTgwResponseModel struct {
	value *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel
	isSet bool
}

func (v NullableBnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) Get() *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel {
	return v.value
}

func (v *NullableBnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) Set(val *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBnsTgwV1ApiListTransitGatewaysModelTgwResponseModel(val *BnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) *NullableBnsTgwV1ApiListTransitGatewaysModelTgwResponseModel {
	return &NullableBnsTgwV1ApiListTransitGatewaysModelTgwResponseModel{value: val, isSet: true}
}

func (v NullableBnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBnsTgwV1ApiListTransitGatewaysModelTgwResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
