/*
bns-tgw API

bns-tgw API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tgw

import (
	"encoding/json"
	"fmt"
)

// checks if the BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel{}

// BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel struct for BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel
type BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel struct {
	// 공유 Attachment 자동 승인 여부
	IsAutoAcceptSharedAttachments bool `json:"is_auto_accept_shared_attachments"`
	// 기본 라우팅 테이블 자동 연결 여부
	IsDefaultRouteTableAssociation bool           `json:"is_default_route_table_association"`
	AssociationDefaultRouteTableId NullableString `json:"association_default_route_table_id,omitempty"`
	AdditionalProperties           map[string]interface{}
}

type _BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel

// NewBnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel instantiates a new BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel(isAutoAcceptSharedAttachments bool, isDefaultRouteTableAssociation bool) *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel {
	this := BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel{}
	this.IsAutoAcceptSharedAttachments = isAutoAcceptSharedAttachments
	this.IsDefaultRouteTableAssociation = isDefaultRouteTableAssociation
	return &this
}

// NewBnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModelWithDefaults instantiates a new BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModelWithDefaults() *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel {
	this := BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel{}
	return &this
}

// GetIsAutoAcceptSharedAttachments returns the IsAutoAcceptSharedAttachments field value
func (o *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) GetIsAutoAcceptSharedAttachments() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsAutoAcceptSharedAttachments
}

// GetIsAutoAcceptSharedAttachmentsOk returns a tuple with the IsAutoAcceptSharedAttachments field value
// and a boolean to check if the value has been set.
func (o *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) GetIsAutoAcceptSharedAttachmentsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsAutoAcceptSharedAttachments, true
}

// SetIsAutoAcceptSharedAttachments sets field value
func (o *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) SetIsAutoAcceptSharedAttachments(v bool) {
	o.IsAutoAcceptSharedAttachments = v
}

// GetIsDefaultRouteTableAssociation returns the IsDefaultRouteTableAssociation field value
func (o *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) GetIsDefaultRouteTableAssociation() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDefaultRouteTableAssociation
}

// GetIsDefaultRouteTableAssociationOk returns a tuple with the IsDefaultRouteTableAssociation field value
// and a boolean to check if the value has been set.
func (o *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) GetIsDefaultRouteTableAssociationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsDefaultRouteTableAssociation, true
}

// SetIsDefaultRouteTableAssociation sets field value
func (o *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) SetIsDefaultRouteTableAssociation(v bool) {
	o.IsDefaultRouteTableAssociation = v
}

// GetAssociationDefaultRouteTableId returns the AssociationDefaultRouteTableId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) GetAssociationDefaultRouteTableId() string {
	if o == nil || IsNil(o.AssociationDefaultRouteTableId.Get()) {
		var ret string
		return ret
	}
	return *o.AssociationDefaultRouteTableId.Get()
}

// GetAssociationDefaultRouteTableIdOk returns a tuple with the AssociationDefaultRouteTableId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) GetAssociationDefaultRouteTableIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssociationDefaultRouteTableId.Get(), o.AssociationDefaultRouteTableId.IsSet()
}

// HasAssociationDefaultRouteTableId returns a boolean if a field has been set.
func (o *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) HasAssociationDefaultRouteTableId() bool {
	if o != nil && o.AssociationDefaultRouteTableId.IsSet() {
		return true
	}

	return false
}

// SetAssociationDefaultRouteTableId gets a reference to the given NullableString and assigns it to the AssociationDefaultRouteTableId field.
func (o *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) SetAssociationDefaultRouteTableId(v string) {
	o.AssociationDefaultRouteTableId.Set(&v)
}

// SetAssociationDefaultRouteTableIdNil sets the value for AssociationDefaultRouteTableId to be an explicit nil
func (o *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) SetAssociationDefaultRouteTableIdNil() {
	o.AssociationDefaultRouteTableId.Set(nil)
}

// UnsetAssociationDefaultRouteTableId ensures that no value is present for AssociationDefaultRouteTableId, not even an explicit nil
func (o *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) UnsetAssociationDefaultRouteTableId() {
	o.AssociationDefaultRouteTableId.Unset()
}

func (o BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["is_auto_accept_shared_attachments"] = o.IsAutoAcceptSharedAttachments
	toSerialize["is_default_route_table_association"] = o.IsDefaultRouteTableAssociation
	if o.AssociationDefaultRouteTableId.IsSet() {
		toSerialize["association_default_route_table_id"] = o.AssociationDefaultRouteTableId.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"is_auto_accept_shared_attachments",
		"is_default_route_table_association",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel := _BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel{}

	err = json.Unmarshal(data, &varBnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel)

	if err != nil {
		return err
	}

	*o = BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel(varBnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "is_auto_accept_shared_attachments")
		delete(additionalProperties, "is_default_route_table_association")
		delete(additionalProperties, "association_default_route_table_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel struct {
	value *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel
	isSet bool
}

func (v NullableBnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) Get() *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel {
	return v.value
}

func (v *NullableBnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) Set(val *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel(val *BnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) *NullableBnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel {
	return &NullableBnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel{value: val, isSet: true}
}

func (v NullableBnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBnsTgwV1ApiUpdateTransitGatewayModelTgwOptionRequestModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
