/*
bns-tgw API

bns-tgw API

API version: 1.2.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tgw

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateTgwAttachmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTgwAttachmentRequest{}

// UpdateTgwAttachmentRequest struct for UpdateTgwAttachmentRequest
type UpdateTgwAttachmentRequest struct {
	// 수정할 Attachment 속성 정보
	Attachment           UpdateTgwAttachment `json:"attachment"`
	AdditionalProperties map[string]interface{}
}

type _UpdateTgwAttachmentRequest UpdateTgwAttachmentRequest

// NewUpdateTgwAttachmentRequest instantiates a new UpdateTgwAttachmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTgwAttachmentRequest(attachment UpdateTgwAttachment) *UpdateTgwAttachmentRequest {
	this := UpdateTgwAttachmentRequest{}
	this.Attachment = attachment
	return &this
}

// NewUpdateTgwAttachmentRequestWithDefaults instantiates a new UpdateTgwAttachmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTgwAttachmentRequestWithDefaults() *UpdateTgwAttachmentRequest {
	this := UpdateTgwAttachmentRequest{}
	return &this
}

// GetAttachment returns the Attachment field value
func (o *UpdateTgwAttachmentRequest) GetAttachment() UpdateTgwAttachment {
	if o == nil {
		var ret UpdateTgwAttachment
		return ret
	}

	return o.Attachment
}

// GetAttachmentOk returns a tuple with the Attachment field value
// and a boolean to check if the value has been set.
func (o *UpdateTgwAttachmentRequest) GetAttachmentOk() (*UpdateTgwAttachment, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attachment, true
}

// SetAttachment sets field value
func (o *UpdateTgwAttachmentRequest) SetAttachment(v UpdateTgwAttachment) {
	o.Attachment = v
}

func (o UpdateTgwAttachmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTgwAttachmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attachment"] = o.Attachment

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateTgwAttachmentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attachment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateTgwAttachmentRequest := _UpdateTgwAttachmentRequest{}

	err = json.Unmarshal(data, &varUpdateTgwAttachmentRequest)

	if err != nil {
		return err
	}

	*o = UpdateTgwAttachmentRequest(varUpdateTgwAttachmentRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "attachment")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateTgwAttachmentRequest struct {
	value *UpdateTgwAttachmentRequest
	isSet bool
}

func (v NullableUpdateTgwAttachmentRequest) Get() *UpdateTgwAttachmentRequest {
	return v.value
}

func (v *NullableUpdateTgwAttachmentRequest) Set(val *UpdateTgwAttachmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTgwAttachmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTgwAttachmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTgwAttachmentRequest(val *UpdateTgwAttachmentRequest) *NullableUpdateTgwAttachmentRequest {
	return &NullableUpdateTgwAttachmentRequest{value: val, isSet: true}
}

func (v NullableUpdateTgwAttachmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTgwAttachmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
