/*
MySQL API

MySQL API

API version: 1.3.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mysql

import (
	"encoding/json"
)

// checks if the DefaultParameterGroupEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefaultParameterGroupEvent{}

// DefaultParameterGroupEvent struct for DefaultParameterGroupEvent
type DefaultParameterGroupEvent struct {
	CreatedAt            NullableString `json:"created_at,omitempty"`
	Description          NullableString `json:"description,omitempty"`
	Name                 NullableString `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DefaultParameterGroupEvent DefaultParameterGroupEvent

// NewDefaultParameterGroupEvent instantiates a new DefaultParameterGroupEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefaultParameterGroupEvent() *DefaultParameterGroupEvent {
	this := DefaultParameterGroupEvent{}
	return &this
}

// NewDefaultParameterGroupEventWithDefaults instantiates a new DefaultParameterGroupEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultParameterGroupEventWithDefaults() *DefaultParameterGroupEvent {
	this := DefaultParameterGroupEvent{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DefaultParameterGroupEvent) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret string
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DefaultParameterGroupEvent) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DefaultParameterGroupEvent) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableString and assigns it to the CreatedAt field.
func (o *DefaultParameterGroupEvent) SetCreatedAt(v string) {
	o.CreatedAt.Set(&v)
}

// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *DefaultParameterGroupEvent) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *DefaultParameterGroupEvent) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DefaultParameterGroupEvent) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DefaultParameterGroupEvent) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *DefaultParameterGroupEvent) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *DefaultParameterGroupEvent) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *DefaultParameterGroupEvent) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *DefaultParameterGroupEvent) UnsetDescription() {
	o.Description.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DefaultParameterGroupEvent) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DefaultParameterGroupEvent) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *DefaultParameterGroupEvent) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *DefaultParameterGroupEvent) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *DefaultParameterGroupEvent) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *DefaultParameterGroupEvent) UnsetName() {
	o.Name.Unset()
}

func (o DefaultParameterGroupEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefaultParameterGroupEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedAt.IsSet() {
		toSerialize["created_at"] = o.CreatedAt.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DefaultParameterGroupEvent) UnmarshalJSON(data []byte) (err error) {
	varDefaultParameterGroupEvent := _DefaultParameterGroupEvent{}

	err = json.Unmarshal(data, &varDefaultParameterGroupEvent)

	if err != nil {
		return err
	}

	*o = DefaultParameterGroupEvent(varDefaultParameterGroupEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "description")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDefaultParameterGroupEvent struct {
	value *DefaultParameterGroupEvent
	isSet bool
}

func (v NullableDefaultParameterGroupEvent) Get() *DefaultParameterGroupEvent {
	return v.value
}

func (v *NullableDefaultParameterGroupEvent) Set(val *DefaultParameterGroupEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultParameterGroupEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultParameterGroupEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultParameterGroupEvent(val *DefaultParameterGroupEvent) *NullableDefaultParameterGroupEvent {
	return &NullableDefaultParameterGroupEvent{value: val, isSet: true}
}

func (v NullableDefaultParameterGroupEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultParameterGroupEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
