/*
MySQL API

MySQL API

API version: 1.3.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mysql

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateMysqlCustomParameterGroupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateMysqlCustomParameterGroupRequest{}

// UpdateMysqlCustomParameterGroupRequest struct for UpdateMysqlCustomParameterGroupRequest
type UpdateMysqlCustomParameterGroupRequest struct {
	// 수정할 MySQL 커스텀 파라미터 그룹 설정 정보
	CustomParameterGroup UpdateMysqlCustomParameterGroup `json:"custom_parameter_group"`
	AdditionalProperties map[string]interface{}
}

type _UpdateMysqlCustomParameterGroupRequest UpdateMysqlCustomParameterGroupRequest

// NewUpdateMysqlCustomParameterGroupRequest instantiates a new UpdateMysqlCustomParameterGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMysqlCustomParameterGroupRequest(customParameterGroup UpdateMysqlCustomParameterGroup) *UpdateMysqlCustomParameterGroupRequest {
	this := UpdateMysqlCustomParameterGroupRequest{}
	this.CustomParameterGroup = customParameterGroup
	return &this
}

// NewUpdateMysqlCustomParameterGroupRequestWithDefaults instantiates a new UpdateMysqlCustomParameterGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMysqlCustomParameterGroupRequestWithDefaults() *UpdateMysqlCustomParameterGroupRequest {
	this := UpdateMysqlCustomParameterGroupRequest{}
	return &this
}

// GetCustomParameterGroup returns the CustomParameterGroup field value
func (o *UpdateMysqlCustomParameterGroupRequest) GetCustomParameterGroup() UpdateMysqlCustomParameterGroup {
	if o == nil {
		var ret UpdateMysqlCustomParameterGroup
		return ret
	}

	return o.CustomParameterGroup
}

// GetCustomParameterGroupOk returns a tuple with the CustomParameterGroup field value
// and a boolean to check if the value has been set.
func (o *UpdateMysqlCustomParameterGroupRequest) GetCustomParameterGroupOk() (*UpdateMysqlCustomParameterGroup, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomParameterGroup, true
}

// SetCustomParameterGroup sets field value
func (o *UpdateMysqlCustomParameterGroupRequest) SetCustomParameterGroup(v UpdateMysqlCustomParameterGroup) {
	o.CustomParameterGroup = v
}

func (o UpdateMysqlCustomParameterGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateMysqlCustomParameterGroupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["custom_parameter_group"] = o.CustomParameterGroup

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateMysqlCustomParameterGroupRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"custom_parameter_group",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateMysqlCustomParameterGroupRequest := _UpdateMysqlCustomParameterGroupRequest{}

	err = json.Unmarshal(data, &varUpdateMysqlCustomParameterGroupRequest)

	if err != nil {
		return err
	}

	*o = UpdateMysqlCustomParameterGroupRequest(varUpdateMysqlCustomParameterGroupRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "custom_parameter_group")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateMysqlCustomParameterGroupRequest struct {
	value *UpdateMysqlCustomParameterGroupRequest
	isSet bool
}

func (v NullableUpdateMysqlCustomParameterGroupRequest) Get() *UpdateMysqlCustomParameterGroupRequest {
	return v.value
}

func (v *NullableUpdateMysqlCustomParameterGroupRequest) Set(val *UpdateMysqlCustomParameterGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMysqlCustomParameterGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMysqlCustomParameterGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMysqlCustomParameterGroupRequest(val *UpdateMysqlCustomParameterGroupRequest) *NullableUpdateMysqlCustomParameterGroupRequest {
	return &NullableUpdateMysqlCustomParameterGroupRequest{value: val, isSet: true}
}

func (v NullableUpdateMysqlCustomParameterGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMysqlCustomParameterGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
