/*
MySQL API

MySQL API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mysql

import (
	"encoding/json"
	"fmt"
)

// checks if the MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel{}

// MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel struct for MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel
type MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel struct {
	DefaultParameterGroupId NullableString `json:"default_parameter_group_id,omitempty"`
	Description             NullableString `json:"description,omitempty"`
	EngineVersion           NullableString `json:"engine_version,omitempty"`
	ExistErrorSync          NullableBool   `json:"exist_error_sync,omitempty"`
	// 해당 커스텀 파라미터 그룹을 사용하는 MySQL 인스턴스 그룹 수
	InstanceGroupCount   int32                               `json:"instance_group_count"`
	IsRollbackPossible   NullableBool                        `json:"is_rollback_possible,omitempty"`
	Name                 NullableString                      `json:"name,omitempty"`
	Id                   NullableString                      `json:"id,omitempty"`
	Parameters           []DataDetailParametersResponseModel `json:"parameters,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel

// NewMysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel instantiates a new MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel(instanceGroupCount int32) *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel {
	this := MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel{}
	this.InstanceGroupCount = instanceGroupCount
	return &this
}

// NewMysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModelWithDefaults instantiates a new MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModelWithDefaults() *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel {
	this := MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel{}
	return &this
}

// GetDefaultParameterGroupId returns the DefaultParameterGroupId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) GetDefaultParameterGroupId() string {
	if o == nil || IsNil(o.DefaultParameterGroupId.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultParameterGroupId.Get()
}

// GetDefaultParameterGroupIdOk returns a tuple with the DefaultParameterGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) GetDefaultParameterGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultParameterGroupId.Get(), o.DefaultParameterGroupId.IsSet()
}

// HasDefaultParameterGroupId returns a boolean if a field has been set.
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) HasDefaultParameterGroupId() bool {
	if o != nil && o.DefaultParameterGroupId.IsSet() {
		return true
	}

	return false
}

// SetDefaultParameterGroupId gets a reference to the given NullableString and assigns it to the DefaultParameterGroupId field.
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) SetDefaultParameterGroupId(v string) {
	o.DefaultParameterGroupId.Set(&v)
}

// SetDefaultParameterGroupIdNil sets the value for DefaultParameterGroupId to be an explicit nil
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) SetDefaultParameterGroupIdNil() {
	o.DefaultParameterGroupId.Set(nil)
}

// UnsetDefaultParameterGroupId ensures that no value is present for DefaultParameterGroupId, not even an explicit nil
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) UnsetDefaultParameterGroupId() {
	o.DefaultParameterGroupId.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) UnsetDescription() {
	o.Description.Unset()
}

// GetEngineVersion returns the EngineVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) GetEngineVersion() string {
	if o == nil || IsNil(o.EngineVersion.Get()) {
		var ret string
		return ret
	}
	return *o.EngineVersion.Get()
}

// GetEngineVersionOk returns a tuple with the EngineVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) GetEngineVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EngineVersion.Get(), o.EngineVersion.IsSet()
}

// HasEngineVersion returns a boolean if a field has been set.
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) HasEngineVersion() bool {
	if o != nil && o.EngineVersion.IsSet() {
		return true
	}

	return false
}

// SetEngineVersion gets a reference to the given NullableString and assigns it to the EngineVersion field.
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) SetEngineVersion(v string) {
	o.EngineVersion.Set(&v)
}

// SetEngineVersionNil sets the value for EngineVersion to be an explicit nil
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) SetEngineVersionNil() {
	o.EngineVersion.Set(nil)
}

// UnsetEngineVersion ensures that no value is present for EngineVersion, not even an explicit nil
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) UnsetEngineVersion() {
	o.EngineVersion.Unset()
}

// GetExistErrorSync returns the ExistErrorSync field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) GetExistErrorSync() bool {
	if o == nil || IsNil(o.ExistErrorSync.Get()) {
		var ret bool
		return ret
	}
	return *o.ExistErrorSync.Get()
}

// GetExistErrorSyncOk returns a tuple with the ExistErrorSync field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) GetExistErrorSyncOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExistErrorSync.Get(), o.ExistErrorSync.IsSet()
}

// HasExistErrorSync returns a boolean if a field has been set.
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) HasExistErrorSync() bool {
	if o != nil && o.ExistErrorSync.IsSet() {
		return true
	}

	return false
}

// SetExistErrorSync gets a reference to the given NullableBool and assigns it to the ExistErrorSync field.
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) SetExistErrorSync(v bool) {
	o.ExistErrorSync.Set(&v)
}

// SetExistErrorSyncNil sets the value for ExistErrorSync to be an explicit nil
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) SetExistErrorSyncNil() {
	o.ExistErrorSync.Set(nil)
}

// UnsetExistErrorSync ensures that no value is present for ExistErrorSync, not even an explicit nil
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) UnsetExistErrorSync() {
	o.ExistErrorSync.Unset()
}

// GetInstanceGroupCount returns the InstanceGroupCount field value
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) GetInstanceGroupCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InstanceGroupCount
}

// GetInstanceGroupCountOk returns a tuple with the InstanceGroupCount field value
// and a boolean to check if the value has been set.
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) GetInstanceGroupCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceGroupCount, true
}

// SetInstanceGroupCount sets field value
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) SetInstanceGroupCount(v int32) {
	o.InstanceGroupCount = v
}

// GetIsRollbackPossible returns the IsRollbackPossible field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) GetIsRollbackPossible() bool {
	if o == nil || IsNil(o.IsRollbackPossible.Get()) {
		var ret bool
		return ret
	}
	return *o.IsRollbackPossible.Get()
}

// GetIsRollbackPossibleOk returns a tuple with the IsRollbackPossible field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) GetIsRollbackPossibleOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsRollbackPossible.Get(), o.IsRollbackPossible.IsSet()
}

// HasIsRollbackPossible returns a boolean if a field has been set.
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) HasIsRollbackPossible() bool {
	if o != nil && o.IsRollbackPossible.IsSet() {
		return true
	}

	return false
}

// SetIsRollbackPossible gets a reference to the given NullableBool and assigns it to the IsRollbackPossible field.
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) SetIsRollbackPossible(v bool) {
	o.IsRollbackPossible.Set(&v)
}

// SetIsRollbackPossibleNil sets the value for IsRollbackPossible to be an explicit nil
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) SetIsRollbackPossibleNil() {
	o.IsRollbackPossible.Set(nil)
}

// UnsetIsRollbackPossible ensures that no value is present for IsRollbackPossible, not even an explicit nil
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) UnsetIsRollbackPossible() {
	o.IsRollbackPossible.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) UnsetName() {
	o.Name.Unset()
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) SetId(v string) {
	o.Id.Set(&v)
}

// SetIdNil sets the value for Id to be an explicit nil
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) UnsetId() {
	o.Id.Unset()
}

// GetParameters returns the Parameters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) GetParameters() []DataDetailParametersResponseModel {
	if o == nil {
		var ret []DataDetailParametersResponseModel
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) GetParametersOk() ([]DataDetailParametersResponseModel, bool) {
	if o == nil || IsNil(o.Parameters) {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given []DataDetailParametersResponseModel and assigns it to the Parameters field.
func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) SetParameters(v []DataDetailParametersResponseModel) {
	o.Parameters = v
}

func (o MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DefaultParameterGroupId.IsSet() {
		toSerialize["default_parameter_group_id"] = o.DefaultParameterGroupId.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.EngineVersion.IsSet() {
		toSerialize["engine_version"] = o.EngineVersion.Get()
	}
	if o.ExistErrorSync.IsSet() {
		toSerialize["exist_error_sync"] = o.ExistErrorSync.Get()
	}
	toSerialize["instance_group_count"] = o.InstanceGroupCount
	if o.IsRollbackPossible.IsSet() {
		toSerialize["is_rollback_possible"] = o.IsRollbackPossible.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.Parameters != nil {
		toSerialize["parameters"] = o.Parameters
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"instance_group_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel := _MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel{}

	err = json.Unmarshal(data, &varMysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel)

	if err != nil {
		return err
	}

	*o = MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel(varMysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "default_parameter_group_id")
		delete(additionalProperties, "description")
		delete(additionalProperties, "engine_version")
		delete(additionalProperties, "exist_error_sync")
		delete(additionalProperties, "instance_group_count")
		delete(additionalProperties, "is_rollback_possible")
		delete(additionalProperties, "name")
		delete(additionalProperties, "id")
		delete(additionalProperties, "parameters")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel struct {
	value *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel
	isSet bool
}

func (v NullableMysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) Get() *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel {
	return v.value
}

func (v *NullableMysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) Set(val *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableMysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableMysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel(val *MysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) *NullableMysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel {
	return &NullableMysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel{value: val, isSet: true}
}

func (v NullableMysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMysqlV1ApiGetMysqlCustomParameterGroupModelCustomParameterGroupResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
