/*
MySQL API

MySQL API

API version: 1.3.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mysql

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateMysqlSecurityGroupsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateMysqlSecurityGroupsRequest{}

// UpdateMysqlSecurityGroupsRequest struct for UpdateMysqlSecurityGroupsRequest
type UpdateMysqlSecurityGroupsRequest struct {
	// MySQL 인스턴스 그룹 보안 그룹 정보
	InstanceGroup        UpdateMysqlSecurityGroups `json:"instance_group"`
	AdditionalProperties map[string]interface{}
}

type _UpdateMysqlSecurityGroupsRequest UpdateMysqlSecurityGroupsRequest

// NewUpdateMysqlSecurityGroupsRequest instantiates a new UpdateMysqlSecurityGroupsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMysqlSecurityGroupsRequest(instanceGroup UpdateMysqlSecurityGroups) *UpdateMysqlSecurityGroupsRequest {
	this := UpdateMysqlSecurityGroupsRequest{}
	this.InstanceGroup = instanceGroup
	return &this
}

// NewUpdateMysqlSecurityGroupsRequestWithDefaults instantiates a new UpdateMysqlSecurityGroupsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMysqlSecurityGroupsRequestWithDefaults() *UpdateMysqlSecurityGroupsRequest {
	this := UpdateMysqlSecurityGroupsRequest{}
	return &this
}

// GetInstanceGroup returns the InstanceGroup field value
func (o *UpdateMysqlSecurityGroupsRequest) GetInstanceGroup() UpdateMysqlSecurityGroups {
	if o == nil {
		var ret UpdateMysqlSecurityGroups
		return ret
	}

	return o.InstanceGroup
}

// GetInstanceGroupOk returns a tuple with the InstanceGroup field value
// and a boolean to check if the value has been set.
func (o *UpdateMysqlSecurityGroupsRequest) GetInstanceGroupOk() (*UpdateMysqlSecurityGroups, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceGroup, true
}

// SetInstanceGroup sets field value
func (o *UpdateMysqlSecurityGroupsRequest) SetInstanceGroup(v UpdateMysqlSecurityGroups) {
	o.InstanceGroup = v
}

func (o UpdateMysqlSecurityGroupsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateMysqlSecurityGroupsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["instance_group"] = o.InstanceGroup

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateMysqlSecurityGroupsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"instance_group",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateMysqlSecurityGroupsRequest := _UpdateMysqlSecurityGroupsRequest{}

	err = json.Unmarshal(data, &varUpdateMysqlSecurityGroupsRequest)

	if err != nil {
		return err
	}

	*o = UpdateMysqlSecurityGroupsRequest(varUpdateMysqlSecurityGroupsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "instance_group")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateMysqlSecurityGroupsRequest struct {
	value *UpdateMysqlSecurityGroupsRequest
	isSet bool
}

func (v NullableUpdateMysqlSecurityGroupsRequest) Get() *UpdateMysqlSecurityGroupsRequest {
	return v.value
}

func (v *NullableUpdateMysqlSecurityGroupsRequest) Set(val *UpdateMysqlSecurityGroupsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMysqlSecurityGroupsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMysqlSecurityGroupsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMysqlSecurityGroupsRequest(val *UpdateMysqlSecurityGroupsRequest) *NullableUpdateMysqlSecurityGroupsRequest {
	return &NullableUpdateMysqlSecurityGroupsRequest{value: val, isSet: true}
}

func (v NullableUpdateMysqlSecurityGroupsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMysqlSecurityGroupsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
