/*
MySQL API

MySQL API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mysql

import (
	"encoding/json"
	"fmt"
)

// checks if the MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel{}

// MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel struct for MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel
type MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel struct {
	Type           NullableBackupScheduleType `json:"type,omitempty"`
	StartTime      NullableString             `json:"start_time,omitempty"`
	ExpiryDuration NullableInt32              `json:"expiry_duration,omitempty"`
	// 백업 스케줄 활성화 여부
	Enabled              bool `json:"enabled"`
	AdditionalProperties map[string]interface{}
}

type _MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel

// NewMysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel instantiates a new MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel(enabled bool) *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel {
	this := MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel{}
	this.Enabled = enabled
	return &this
}

// NewMysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModelWithDefaults instantiates a new MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModelWithDefaults() *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel {
	this := MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) GetType() BackupScheduleType {
	if o == nil || IsNil(o.Type.Get()) {
		var ret BackupScheduleType
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) GetTypeOk() (*BackupScheduleType, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableBackupScheduleType and assigns it to the Type field.
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) SetType(v BackupScheduleType) {
	o.Type.Set(&v)
}

// SetTypeNil sets the value for Type to be an explicit nil
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) UnsetType() {
	o.Type.Unset()
}

// GetStartTime returns the StartTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) GetStartTime() string {
	if o == nil || IsNil(o.StartTime.Get()) {
		var ret string
		return ret
	}
	return *o.StartTime.Get()
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) GetStartTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartTime.Get(), o.StartTime.IsSet()
}

// HasStartTime returns a boolean if a field has been set.
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) HasStartTime() bool {
	if o != nil && o.StartTime.IsSet() {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given NullableString and assigns it to the StartTime field.
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) SetStartTime(v string) {
	o.StartTime.Set(&v)
}

// SetStartTimeNil sets the value for StartTime to be an explicit nil
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) SetStartTimeNil() {
	o.StartTime.Set(nil)
}

// UnsetStartTime ensures that no value is present for StartTime, not even an explicit nil
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) UnsetStartTime() {
	o.StartTime.Unset()
}

// GetExpiryDuration returns the ExpiryDuration field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) GetExpiryDuration() int32 {
	if o == nil || IsNil(o.ExpiryDuration.Get()) {
		var ret int32
		return ret
	}
	return *o.ExpiryDuration.Get()
}

// GetExpiryDurationOk returns a tuple with the ExpiryDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) GetExpiryDurationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiryDuration.Get(), o.ExpiryDuration.IsSet()
}

// HasExpiryDuration returns a boolean if a field has been set.
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) HasExpiryDuration() bool {
	if o != nil && o.ExpiryDuration.IsSet() {
		return true
	}

	return false
}

// SetExpiryDuration gets a reference to the given NullableInt32 and assigns it to the ExpiryDuration field.
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) SetExpiryDuration(v int32) {
	o.ExpiryDuration.Set(&v)
}

// SetExpiryDurationNil sets the value for ExpiryDuration to be an explicit nil
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) SetExpiryDurationNil() {
	o.ExpiryDuration.Set(nil)
}

// UnsetExpiryDuration ensures that no value is present for ExpiryDuration, not even an explicit nil
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) UnsetExpiryDuration() {
	o.ExpiryDuration.Unset()
}

// GetEnabled returns the Enabled field value
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) SetEnabled(v bool) {
	o.Enabled = v
}

func (o MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}
	if o.StartTime.IsSet() {
		toSerialize["start_time"] = o.StartTime.Get()
	}
	if o.ExpiryDuration.IsSet() {
		toSerialize["expiry_duration"] = o.ExpiryDuration.Get()
	}
	toSerialize["enabled"] = o.Enabled

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel := _MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel{}

	err = json.Unmarshal(data, &varMysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel)

	if err != nil {
		return err
	}

	*o = MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel(varMysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "start_time")
		delete(additionalProperties, "expiry_duration")
		delete(additionalProperties, "enabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel struct {
	value *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel
	isSet bool
}

func (v NullableMysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) Get() *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel {
	return v.value
}

func (v *NullableMysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) Set(val *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) {
	v.value = val
	v.isSet = true
}

func (v NullableMysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) IsSet() bool {
	return v.isSet
}

func (v *NullableMysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel(val *MysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) *NullableMysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel {
	return &NullableMysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel{value: val, isSet: true}
}

func (v NullableMysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMysqlV1ApiCreateMysqlInstanceGroupModelBackupScheduleRequestModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
