/*
MySQL API

MySQL API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mysql

import (
	"encoding/json"
	"fmt"
)

// checks if the MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel{}

// MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel struct for MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel
type MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel struct {
	// 기본 데이터베이스 사용자 이름
	DatabaseUserName string `json:"database_user_name"`
	// Primary 포트 번호
	PrimaryPort int32 `json:"primary_port"`
	// Standby 포트 번호
	StandbyPort int32 `json:"standby_port"`
	// MySQL 엔진 버전
	EngineVersion string `json:"engine_version"`
	// 인스턴스 Flavor ID
	FlavorId string `json:"flavor_id"`
	// vCPU 개수
	Vcpu int32 `json:"vcpu"`
	// 메모리 크기 (MB)
	Memory int32 `json:"memory"`
	// 로그 디스크 크기 (GB)
	LogDiskSize int32 `json:"log_disk_size"`
	// 데이터 디스크 크기 (GB)
	DataDiskSize int32 `json:"data_disk_size"`
	// MySQL 인스턴스 그룹 유형
	InstanceGroupType ClusterType `json:"instance_group_type"`
	// MySQL 인스턴스 그룹의 노드 크기
	NodeSize             int32 `json:"node_size"`
	AdditionalProperties map[string]interface{}
}

type _MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel

// NewMysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel instantiates a new MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel(databaseUserName string, primaryPort int32, standbyPort int32, engineVersion string, flavorId string, vcpu int32, memory int32, logDiskSize int32, dataDiskSize int32, instanceGroupType ClusterType, nodeSize int32) *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel {
	this := MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel{}
	this.DatabaseUserName = databaseUserName
	this.PrimaryPort = primaryPort
	this.StandbyPort = standbyPort
	this.EngineVersion = engineVersion
	this.FlavorId = flavorId
	this.Vcpu = vcpu
	this.Memory = memory
	this.LogDiskSize = logDiskSize
	this.DataDiskSize = dataDiskSize
	this.InstanceGroupType = instanceGroupType
	this.NodeSize = nodeSize
	return &this
}

// NewMysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModelWithDefaults instantiates a new MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModelWithDefaults() *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel {
	this := MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel{}
	return &this
}

// GetDatabaseUserName returns the DatabaseUserName field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetDatabaseUserName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DatabaseUserName
}

// GetDatabaseUserNameOk returns a tuple with the DatabaseUserName field value
// and a boolean to check if the value has been set.
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetDatabaseUserNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DatabaseUserName, true
}

// SetDatabaseUserName sets field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) SetDatabaseUserName(v string) {
	o.DatabaseUserName = v
}

// GetPrimaryPort returns the PrimaryPort field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetPrimaryPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PrimaryPort
}

// GetPrimaryPortOk returns a tuple with the PrimaryPort field value
// and a boolean to check if the value has been set.
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetPrimaryPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrimaryPort, true
}

// SetPrimaryPort sets field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) SetPrimaryPort(v int32) {
	o.PrimaryPort = v
}

// GetStandbyPort returns the StandbyPort field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetStandbyPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StandbyPort
}

// GetStandbyPortOk returns a tuple with the StandbyPort field value
// and a boolean to check if the value has been set.
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetStandbyPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StandbyPort, true
}

// SetStandbyPort sets field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) SetStandbyPort(v int32) {
	o.StandbyPort = v
}

// GetEngineVersion returns the EngineVersion field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetEngineVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EngineVersion
}

// GetEngineVersionOk returns a tuple with the EngineVersion field value
// and a boolean to check if the value has been set.
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetEngineVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EngineVersion, true
}

// SetEngineVersion sets field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) SetEngineVersion(v string) {
	o.EngineVersion = v
}

// GetFlavorId returns the FlavorId field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetFlavorId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FlavorId
}

// GetFlavorIdOk returns a tuple with the FlavorId field value
// and a boolean to check if the value has been set.
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetFlavorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FlavorId, true
}

// SetFlavorId sets field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) SetFlavorId(v string) {
	o.FlavorId = v
}

// GetVcpu returns the Vcpu field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetVcpu() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Vcpu
}

// GetVcpuOk returns a tuple with the Vcpu field value
// and a boolean to check if the value has been set.
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetVcpuOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vcpu, true
}

// SetVcpu sets field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) SetVcpu(v int32) {
	o.Vcpu = v
}

// GetMemory returns the Memory field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetMemory() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value
// and a boolean to check if the value has been set.
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetMemoryOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Memory, true
}

// SetMemory sets field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) SetMemory(v int32) {
	o.Memory = v
}

// GetLogDiskSize returns the LogDiskSize field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetLogDiskSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LogDiskSize
}

// GetLogDiskSizeOk returns a tuple with the LogDiskSize field value
// and a boolean to check if the value has been set.
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetLogDiskSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogDiskSize, true
}

// SetLogDiskSize sets field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) SetLogDiskSize(v int32) {
	o.LogDiskSize = v
}

// GetDataDiskSize returns the DataDiskSize field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetDataDiskSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DataDiskSize
}

// GetDataDiskSizeOk returns a tuple with the DataDiskSize field value
// and a boolean to check if the value has been set.
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetDataDiskSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataDiskSize, true
}

// SetDataDiskSize sets field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) SetDataDiskSize(v int32) {
	o.DataDiskSize = v
}

// GetInstanceGroupType returns the InstanceGroupType field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetInstanceGroupType() ClusterType {
	if o == nil {
		var ret ClusterType
		return ret
	}

	return o.InstanceGroupType
}

// GetInstanceGroupTypeOk returns a tuple with the InstanceGroupType field value
// and a boolean to check if the value has been set.
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetInstanceGroupTypeOk() (*ClusterType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceGroupType, true
}

// SetInstanceGroupType sets field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) SetInstanceGroupType(v ClusterType) {
	o.InstanceGroupType = v
}

// GetNodeSize returns the NodeSize field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetNodeSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NodeSize
}

// GetNodeSizeOk returns a tuple with the NodeSize field value
// and a boolean to check if the value has been set.
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) GetNodeSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeSize, true
}

// SetNodeSize sets field value
func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) SetNodeSize(v int32) {
	o.NodeSize = v
}

func (o MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["database_user_name"] = o.DatabaseUserName
	toSerialize["primary_port"] = o.PrimaryPort
	toSerialize["standby_port"] = o.StandbyPort
	toSerialize["engine_version"] = o.EngineVersion
	toSerialize["flavor_id"] = o.FlavorId
	toSerialize["vcpu"] = o.Vcpu
	toSerialize["memory"] = o.Memory
	toSerialize["log_disk_size"] = o.LogDiskSize
	toSerialize["data_disk_size"] = o.DataDiskSize
	toSerialize["instance_group_type"] = o.InstanceGroupType
	toSerialize["node_size"] = o.NodeSize

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"database_user_name",
		"primary_port",
		"standby_port",
		"engine_version",
		"flavor_id",
		"vcpu",
		"memory",
		"log_disk_size",
		"data_disk_size",
		"instance_group_type",
		"node_size",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel := _MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel{}

	err = json.Unmarshal(data, &varMysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel)

	if err != nil {
		return err
	}

	*o = MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel(varMysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "database_user_name")
		delete(additionalProperties, "primary_port")
		delete(additionalProperties, "standby_port")
		delete(additionalProperties, "engine_version")
		delete(additionalProperties, "flavor_id")
		delete(additionalProperties, "vcpu")
		delete(additionalProperties, "memory")
		delete(additionalProperties, "log_disk_size")
		delete(additionalProperties, "data_disk_size")
		delete(additionalProperties, "instance_group_type")
		delete(additionalProperties, "node_size")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel struct {
	value *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel
	isSet bool
}

func (v NullableMysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) Get() *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel {
	return v.value
}

func (v *NullableMysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) Set(val *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableMysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableMysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel(val *MysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) *NullableMysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel {
	return &NullableMysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel{value: val, isSet: true}
}

func (v NullableMysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMysqlV1ApiGetMysqlInstanceGroupModelSpecContentResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
