/*
MySQL API

MySQL API

API version: 1.3.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mysql

import (
	"encoding/json"
	"fmt"
)

// checks if the GetMysqlBackupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMysqlBackupResponse{}

// GetMysqlBackupResponse struct for GetMysqlBackupResponse
type GetMysqlBackupResponse struct {
	// 조회된 MySQL 백업의 상세 정보
	Backup               MySQLBackup `json:"backup"`
	AdditionalProperties map[string]interface{}
}

type _GetMysqlBackupResponse GetMysqlBackupResponse

// NewGetMysqlBackupResponse instantiates a new GetMysqlBackupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMysqlBackupResponse(backup MySQLBackup) *GetMysqlBackupResponse {
	this := GetMysqlBackupResponse{}
	this.Backup = backup
	return &this
}

// NewGetMysqlBackupResponseWithDefaults instantiates a new GetMysqlBackupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMysqlBackupResponseWithDefaults() *GetMysqlBackupResponse {
	this := GetMysqlBackupResponse{}
	return &this
}

// GetBackup returns the Backup field value
func (o *GetMysqlBackupResponse) GetBackup() MySQLBackup {
	if o == nil {
		var ret MySQLBackup
		return ret
	}

	return o.Backup
}

// GetBackupOk returns a tuple with the Backup field value
// and a boolean to check if the value has been set.
func (o *GetMysqlBackupResponse) GetBackupOk() (*MySQLBackup, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Backup, true
}

// SetBackup sets field value
func (o *GetMysqlBackupResponse) SetBackup(v MySQLBackup) {
	o.Backup = v
}

func (o GetMysqlBackupResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMysqlBackupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["backup"] = o.Backup

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetMysqlBackupResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"backup",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetMysqlBackupResponse := _GetMysqlBackupResponse{}

	err = json.Unmarshal(data, &varGetMysqlBackupResponse)

	if err != nil {
		return err
	}

	*o = GetMysqlBackupResponse(varGetMysqlBackupResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "backup")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetMysqlBackupResponse struct {
	value *GetMysqlBackupResponse
	isSet bool
}

func (v NullableGetMysqlBackupResponse) Get() *GetMysqlBackupResponse {
	return v.value
}

func (v *NullableGetMysqlBackupResponse) Set(val *GetMysqlBackupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMysqlBackupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMysqlBackupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMysqlBackupResponse(val *GetMysqlBackupResponse) *NullableGetMysqlBackupResponse {
	return &NullableGetMysqlBackupResponse{value: val, isSet: true}
}

func (v NullableGetMysqlBackupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMysqlBackupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
