/*
Beyond Networking Service(BNS) Load Balancer API

BNS Load Balancer API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loadbalancer

import (
	"encoding/json"
	"fmt"
)

// checks if the ListenerListModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListenerListModel{}

// ListenerListModel struct for ListenerListModel
type ListenerListModel struct {
	Listeners            []BnsLoadBalancerV1ApiListListenersModelListenerModel `json:"listeners,omitempty"`
	Pagination           PaginationModel                                       `json:"pagination"`
	AdditionalProperties map[string]interface{}
}

type _ListenerListModel ListenerListModel

// NewListenerListModel instantiates a new ListenerListModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListenerListModel(pagination PaginationModel) *ListenerListModel {
	this := ListenerListModel{}
	this.Pagination = pagination
	return &this
}

// NewListenerListModelWithDefaults instantiates a new ListenerListModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListenerListModelWithDefaults() *ListenerListModel {
	this := ListenerListModel{}
	return &this
}

// GetListeners returns the Listeners field value if set, zero value otherwise.
func (o *ListenerListModel) GetListeners() []BnsLoadBalancerV1ApiListListenersModelListenerModel {
	if o == nil || IsNil(o.Listeners) {
		var ret []BnsLoadBalancerV1ApiListListenersModelListenerModel
		return ret
	}
	return o.Listeners
}

// GetListenersOk returns a tuple with the Listeners field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListenerListModel) GetListenersOk() ([]BnsLoadBalancerV1ApiListListenersModelListenerModel, bool) {
	if o == nil || IsNil(o.Listeners) {
		return nil, false
	}
	return o.Listeners, true
}

// HasListeners returns a boolean if a field has been set.
func (o *ListenerListModel) HasListeners() bool {
	if o != nil && !IsNil(o.Listeners) {
		return true
	}

	return false
}

// SetListeners gets a reference to the given []BnsLoadBalancerV1ApiListListenersModelListenerModel and assigns it to the Listeners field.
func (o *ListenerListModel) SetListeners(v []BnsLoadBalancerV1ApiListListenersModelListenerModel) {
	o.Listeners = v
}

// GetPagination returns the Pagination field value
func (o *ListenerListModel) GetPagination() PaginationModel {
	if o == nil {
		var ret PaginationModel
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *ListenerListModel) GetPaginationOk() (*PaginationModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *ListenerListModel) SetPagination(v PaginationModel) {
	o.Pagination = v
}

func (o ListenerListModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListenerListModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Listeners) {
		toSerialize["listeners"] = o.Listeners
	}
	toSerialize["pagination"] = o.Pagination

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListenerListModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListenerListModel := _ListenerListModel{}

	err = json.Unmarshal(data, &varListenerListModel)

	if err != nil {
		return err
	}

	*o = ListenerListModel(varListenerListModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "listeners")
		delete(additionalProperties, "pagination")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListenerListModel struct {
	value *ListenerListModel
	isSet bool
}

func (v NullableListenerListModel) Get() *ListenerListModel {
	return v.value
}

func (v *NullableListenerListModel) Set(val *ListenerListModel) {
	v.value = val
	v.isSet = true
}

func (v NullableListenerListModel) IsSet() bool {
	return v.isSet
}

func (v *NullableListenerListModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListenerListModel(val *ListenerListModel) *NullableListenerListModel {
	return &NullableListenerListModel{value: val, isSet: true}
}

func (v NullableListenerListModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListenerListModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
