/*
Beyond Networking Service(BNS) Load Balancer API

BNS Load Balancer API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loadbalancer

import (
	"encoding/json"
	"fmt"
)

// checks if the BodyCreateHealthMonitor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BodyCreateHealthMonitor{}

// BodyCreateHealthMonitor struct for BodyCreateHealthMonitor
type BodyCreateHealthMonitor struct {
	HealthMonitor        CreateHealthMonitor `json:"health_monitor"`
	AdditionalProperties map[string]interface{}
}

type _BodyCreateHealthMonitor BodyCreateHealthMonitor

// NewBodyCreateHealthMonitor instantiates a new BodyCreateHealthMonitor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBodyCreateHealthMonitor(healthMonitor CreateHealthMonitor) *BodyCreateHealthMonitor {
	this := BodyCreateHealthMonitor{}
	this.HealthMonitor = healthMonitor
	return &this
}

// NewBodyCreateHealthMonitorWithDefaults instantiates a new BodyCreateHealthMonitor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBodyCreateHealthMonitorWithDefaults() *BodyCreateHealthMonitor {
	this := BodyCreateHealthMonitor{}
	return &this
}

// GetHealthMonitor returns the HealthMonitor field value
func (o *BodyCreateHealthMonitor) GetHealthMonitor() CreateHealthMonitor {
	if o == nil {
		var ret CreateHealthMonitor
		return ret
	}

	return o.HealthMonitor
}

// GetHealthMonitorOk returns a tuple with the HealthMonitor field value
// and a boolean to check if the value has been set.
func (o *BodyCreateHealthMonitor) GetHealthMonitorOk() (*CreateHealthMonitor, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HealthMonitor, true
}

// SetHealthMonitor sets field value
func (o *BodyCreateHealthMonitor) SetHealthMonitor(v CreateHealthMonitor) {
	o.HealthMonitor = v
}

func (o BodyCreateHealthMonitor) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BodyCreateHealthMonitor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["health_monitor"] = o.HealthMonitor

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BodyCreateHealthMonitor) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"health_monitor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBodyCreateHealthMonitor := _BodyCreateHealthMonitor{}

	err = json.Unmarshal(data, &varBodyCreateHealthMonitor)

	if err != nil {
		return err
	}

	*o = BodyCreateHealthMonitor(varBodyCreateHealthMonitor)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "health_monitor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBodyCreateHealthMonitor struct {
	value *BodyCreateHealthMonitor
	isSet bool
}

func (v NullableBodyCreateHealthMonitor) Get() *BodyCreateHealthMonitor {
	return v.value
}

func (v *NullableBodyCreateHealthMonitor) Set(val *BodyCreateHealthMonitor) {
	v.value = val
	v.isSet = true
}

func (v NullableBodyCreateHealthMonitor) IsSet() bool {
	return v.isSet
}

func (v *NullableBodyCreateHealthMonitor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBodyCreateHealthMonitor(val *BodyCreateHealthMonitor) *NullableBodyCreateHealthMonitor {
	return &NullableBodyCreateHealthMonitor{value: val, isSet: true}
}

func (v NullableBodyCreateHealthMonitor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBodyCreateHealthMonitor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
