/*
Beyond Networking Service(BNS) Load Balancer API

BNS Load Balancer API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loadbalancer

import (
	"encoding/json"
	"fmt"
)

// checks if the BnsLoadBalancerV1ApiGetTargetModelSubnetModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BnsLoadBalancerV1ApiGetTargetModelSubnetModel{}

// BnsLoadBalancerV1ApiGetTargetModelSubnetModel struct for BnsLoadBalancerV1ApiGetTargetModelSubnetModel
type BnsLoadBalancerV1ApiGetTargetModelSubnetModel struct {
	// 서브넷의 고유 ID
	Id                   string                   `json:"id"`
	Name                 NullableString           `json:"name,omitempty"`
	CidrBlock            NullableString           `json:"cidr_block,omitempty"`
	AvailabilityZone     NullableAvailabilityZone `json:"availability_zone,omitempty"`
	HealthCheckIps       []string                 `json:"health_check_ips,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BnsLoadBalancerV1ApiGetTargetModelSubnetModel BnsLoadBalancerV1ApiGetTargetModelSubnetModel

// NewBnsLoadBalancerV1ApiGetTargetModelSubnetModel instantiates a new BnsLoadBalancerV1ApiGetTargetModelSubnetModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBnsLoadBalancerV1ApiGetTargetModelSubnetModel(id string) *BnsLoadBalancerV1ApiGetTargetModelSubnetModel {
	this := BnsLoadBalancerV1ApiGetTargetModelSubnetModel{}
	this.Id = id
	return &this
}

// NewBnsLoadBalancerV1ApiGetTargetModelSubnetModelWithDefaults instantiates a new BnsLoadBalancerV1ApiGetTargetModelSubnetModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBnsLoadBalancerV1ApiGetTargetModelSubnetModelWithDefaults() *BnsLoadBalancerV1ApiGetTargetModelSubnetModel {
	this := BnsLoadBalancerV1ApiGetTargetModelSubnetModel{}
	return &this
}

// GetId returns the Id field value
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) UnsetName() {
	o.Name.Unset()
}

// GetCidrBlock returns the CidrBlock field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) GetCidrBlock() string {
	if o == nil || IsNil(o.CidrBlock.Get()) {
		var ret string
		return ret
	}
	return *o.CidrBlock.Get()
}

// GetCidrBlockOk returns a tuple with the CidrBlock field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) GetCidrBlockOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CidrBlock.Get(), o.CidrBlock.IsSet()
}

// HasCidrBlock returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) HasCidrBlock() bool {
	if o != nil && o.CidrBlock.IsSet() {
		return true
	}

	return false
}

// SetCidrBlock gets a reference to the given NullableString and assigns it to the CidrBlock field.
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) SetCidrBlock(v string) {
	o.CidrBlock.Set(&v)
}

// SetCidrBlockNil sets the value for CidrBlock to be an explicit nil
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) SetCidrBlockNil() {
	o.CidrBlock.Set(nil)
}

// UnsetCidrBlock ensures that no value is present for CidrBlock, not even an explicit nil
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) UnsetCidrBlock() {
	o.CidrBlock.Unset()
}

// GetAvailabilityZone returns the AvailabilityZone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) GetAvailabilityZone() AvailabilityZone {
	if o == nil || IsNil(o.AvailabilityZone.Get()) {
		var ret AvailabilityZone
		return ret
	}
	return *o.AvailabilityZone.Get()
}

// GetAvailabilityZoneOk returns a tuple with the AvailabilityZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) GetAvailabilityZoneOk() (*AvailabilityZone, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvailabilityZone.Get(), o.AvailabilityZone.IsSet()
}

// HasAvailabilityZone returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) HasAvailabilityZone() bool {
	if o != nil && o.AvailabilityZone.IsSet() {
		return true
	}

	return false
}

// SetAvailabilityZone gets a reference to the given NullableAvailabilityZone and assigns it to the AvailabilityZone field.
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) SetAvailabilityZone(v AvailabilityZone) {
	o.AvailabilityZone.Set(&v)
}

// SetAvailabilityZoneNil sets the value for AvailabilityZone to be an explicit nil
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) SetAvailabilityZoneNil() {
	o.AvailabilityZone.Set(nil)
}

// UnsetAvailabilityZone ensures that no value is present for AvailabilityZone, not even an explicit nil
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) UnsetAvailabilityZone() {
	o.AvailabilityZone.Unset()
}

// GetHealthCheckIps returns the HealthCheckIps field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) GetHealthCheckIps() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.HealthCheckIps
}

// GetHealthCheckIpsOk returns a tuple with the HealthCheckIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) GetHealthCheckIpsOk() ([]string, bool) {
	if o == nil || IsNil(o.HealthCheckIps) {
		return nil, false
	}
	return o.HealthCheckIps, true
}

// HasHealthCheckIps returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) HasHealthCheckIps() bool {
	if o != nil && !IsNil(o.HealthCheckIps) {
		return true
	}

	return false
}

// SetHealthCheckIps gets a reference to the given []string and assigns it to the HealthCheckIps field.
func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) SetHealthCheckIps(v []string) {
	o.HealthCheckIps = v
}

func (o BnsLoadBalancerV1ApiGetTargetModelSubnetModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BnsLoadBalancerV1ApiGetTargetModelSubnetModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.CidrBlock.IsSet() {
		toSerialize["cidr_block"] = o.CidrBlock.Get()
	}
	if o.AvailabilityZone.IsSet() {
		toSerialize["availability_zone"] = o.AvailabilityZone.Get()
	}
	if o.HealthCheckIps != nil {
		toSerialize["health_check_ips"] = o.HealthCheckIps
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBnsLoadBalancerV1ApiGetTargetModelSubnetModel := _BnsLoadBalancerV1ApiGetTargetModelSubnetModel{}

	err = json.Unmarshal(data, &varBnsLoadBalancerV1ApiGetTargetModelSubnetModel)

	if err != nil {
		return err
	}

	*o = BnsLoadBalancerV1ApiGetTargetModelSubnetModel(varBnsLoadBalancerV1ApiGetTargetModelSubnetModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "cidr_block")
		delete(additionalProperties, "availability_zone")
		delete(additionalProperties, "health_check_ips")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBnsLoadBalancerV1ApiGetTargetModelSubnetModel struct {
	value *BnsLoadBalancerV1ApiGetTargetModelSubnetModel
	isSet bool
}

func (v NullableBnsLoadBalancerV1ApiGetTargetModelSubnetModel) Get() *BnsLoadBalancerV1ApiGetTargetModelSubnetModel {
	return v.value
}

func (v *NullableBnsLoadBalancerV1ApiGetTargetModelSubnetModel) Set(val *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBnsLoadBalancerV1ApiGetTargetModelSubnetModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBnsLoadBalancerV1ApiGetTargetModelSubnetModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBnsLoadBalancerV1ApiGetTargetModelSubnetModel(val *BnsLoadBalancerV1ApiGetTargetModelSubnetModel) *NullableBnsLoadBalancerV1ApiGetTargetModelSubnetModel {
	return &NullableBnsLoadBalancerV1ApiGetTargetModelSubnetModel{value: val, isSet: true}
}

func (v NullableBnsLoadBalancerV1ApiGetTargetModelSubnetModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBnsLoadBalancerV1ApiGetTargetModelSubnetModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
