/*
Beyond Networking Service(BNS) Load Balancer API

BNS Load Balancer API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loadbalancer

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel{}

// BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel struct for BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel
type BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel struct {
	// 로드 밸런서의 ID
	Id string `json:"id"`
	// 로드 밸런서의 이름
	Name               string                              `json:"name"`
	Description        NullableString                      `json:"description,omitempty"`
	ProvisioningStatus NullableProvisioningStatus          `json:"provisioning_status,omitempty"`
	OperatingStatus    NullableLoadBalancerOperatingStatus `json:"operating_status,omitempty"`
	AccessLogs         NullableAccessLogs                  `json:"access_logs,omitempty"`
	// 해당 리소스가 속한 프로젝트의 ID
	ProjectId        string                                                       `json:"project_id"`
	CreatedAt        NullableTime                                                 `json:"created_at,omitempty"`
	UpdatedAt        NullableTime                                                 `json:"updated_at,omitempty"`
	SubnetId         NullableString                                               `json:"subnet_id,omitempty"`
	Listeners        []BnsLoadBalancerV1ApiUpdateLoadBalancerModelListenerIdModel `json:"listeners,omitempty"`
	Provider         NullableString                                               `json:"provider,omitempty"`
	FlavorId         NullableString                                               `json:"flavor_id,omitempty"`
	AvailabilityZone NullableAvailabilityZone                                     `json:"availability_zone,omitempty"`
	// 연결된 대상 그룹 수
	TargetGroupCount     int32 `json:"target_group_count"`
	AdditionalProperties map[string]interface{}
}

type _BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel

// NewBnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel instantiates a new BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel(id string, name string, projectId string, targetGroupCount int32) *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel {
	this := BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel{}
	this.Id = id
	this.Name = name
	this.ProjectId = projectId
	this.TargetGroupCount = targetGroupCount
	return &this
}

// NewBnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModelWithDefaults instantiates a new BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModelWithDefaults() *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel {
	this := BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel{}
	return &this
}

// GetId returns the Id field value
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) UnsetDescription() {
	o.Description.Unset()
}

// GetProvisioningStatus returns the ProvisioningStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetProvisioningStatus() ProvisioningStatus {
	if o == nil || IsNil(o.ProvisioningStatus.Get()) {
		var ret ProvisioningStatus
		return ret
	}
	return *o.ProvisioningStatus.Get()
}

// GetProvisioningStatusOk returns a tuple with the ProvisioningStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetProvisioningStatusOk() (*ProvisioningStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProvisioningStatus.Get(), o.ProvisioningStatus.IsSet()
}

// HasProvisioningStatus returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) HasProvisioningStatus() bool {
	if o != nil && o.ProvisioningStatus.IsSet() {
		return true
	}

	return false
}

// SetProvisioningStatus gets a reference to the given NullableProvisioningStatus and assigns it to the ProvisioningStatus field.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetProvisioningStatus(v ProvisioningStatus) {
	o.ProvisioningStatus.Set(&v)
}

// SetProvisioningStatusNil sets the value for ProvisioningStatus to be an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetProvisioningStatusNil() {
	o.ProvisioningStatus.Set(nil)
}

// UnsetProvisioningStatus ensures that no value is present for ProvisioningStatus, not even an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) UnsetProvisioningStatus() {
	o.ProvisioningStatus.Unset()
}

// GetOperatingStatus returns the OperatingStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetOperatingStatus() LoadBalancerOperatingStatus {
	if o == nil || IsNil(o.OperatingStatus.Get()) {
		var ret LoadBalancerOperatingStatus
		return ret
	}
	return *o.OperatingStatus.Get()
}

// GetOperatingStatusOk returns a tuple with the OperatingStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetOperatingStatusOk() (*LoadBalancerOperatingStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.OperatingStatus.Get(), o.OperatingStatus.IsSet()
}

// HasOperatingStatus returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) HasOperatingStatus() bool {
	if o != nil && o.OperatingStatus.IsSet() {
		return true
	}

	return false
}

// SetOperatingStatus gets a reference to the given NullableLoadBalancerOperatingStatus and assigns it to the OperatingStatus field.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetOperatingStatus(v LoadBalancerOperatingStatus) {
	o.OperatingStatus.Set(&v)
}

// SetOperatingStatusNil sets the value for OperatingStatus to be an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetOperatingStatusNil() {
	o.OperatingStatus.Set(nil)
}

// UnsetOperatingStatus ensures that no value is present for OperatingStatus, not even an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) UnsetOperatingStatus() {
	o.OperatingStatus.Unset()
}

// GetAccessLogs returns the AccessLogs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetAccessLogs() AccessLogs {
	if o == nil || IsNil(o.AccessLogs.Get()) {
		var ret AccessLogs
		return ret
	}
	return *o.AccessLogs.Get()
}

// GetAccessLogsOk returns a tuple with the AccessLogs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetAccessLogsOk() (*AccessLogs, bool) {
	if o == nil {
		return nil, false
	}
	return o.AccessLogs.Get(), o.AccessLogs.IsSet()
}

// HasAccessLogs returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) HasAccessLogs() bool {
	if o != nil && o.AccessLogs.IsSet() {
		return true
	}

	return false
}

// SetAccessLogs gets a reference to the given NullableAccessLogs and assigns it to the AccessLogs field.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetAccessLogs(v AccessLogs) {
	o.AccessLogs.Set(&v)
}

// SetAccessLogsNil sets the value for AccessLogs to be an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetAccessLogsNil() {
	o.AccessLogs.Set(nil)
}

// UnsetAccessLogs ensures that no value is present for AccessLogs, not even an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) UnsetAccessLogs() {
	o.AccessLogs.Unset()
}

// GetProjectId returns the ProjectId field value
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetProjectId(v string) {
	o.ProjectId = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableTime and assigns it to the CreatedAt field.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetCreatedAt(v time.Time) {
	o.CreatedAt.Set(&v)
}

// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}

// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

// GetSubnetId returns the SubnetId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetSubnetId() string {
	if o == nil || IsNil(o.SubnetId.Get()) {
		var ret string
		return ret
	}
	return *o.SubnetId.Get()
}

// GetSubnetIdOk returns a tuple with the SubnetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetSubnetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubnetId.Get(), o.SubnetId.IsSet()
}

// HasSubnetId returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) HasSubnetId() bool {
	if o != nil && o.SubnetId.IsSet() {
		return true
	}

	return false
}

// SetSubnetId gets a reference to the given NullableString and assigns it to the SubnetId field.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetSubnetId(v string) {
	o.SubnetId.Set(&v)
}

// SetSubnetIdNil sets the value for SubnetId to be an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetSubnetIdNil() {
	o.SubnetId.Set(nil)
}

// UnsetSubnetId ensures that no value is present for SubnetId, not even an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) UnsetSubnetId() {
	o.SubnetId.Unset()
}

// GetListeners returns the Listeners field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetListeners() []BnsLoadBalancerV1ApiUpdateLoadBalancerModelListenerIdModel {
	if o == nil {
		var ret []BnsLoadBalancerV1ApiUpdateLoadBalancerModelListenerIdModel
		return ret
	}
	return o.Listeners
}

// GetListenersOk returns a tuple with the Listeners field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetListenersOk() ([]BnsLoadBalancerV1ApiUpdateLoadBalancerModelListenerIdModel, bool) {
	if o == nil || IsNil(o.Listeners) {
		return nil, false
	}
	return o.Listeners, true
}

// HasListeners returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) HasListeners() bool {
	if o != nil && !IsNil(o.Listeners) {
		return true
	}

	return false
}

// SetListeners gets a reference to the given []BnsLoadBalancerV1ApiUpdateLoadBalancerModelListenerIdModel and assigns it to the Listeners field.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetListeners(v []BnsLoadBalancerV1ApiUpdateLoadBalancerModelListenerIdModel) {
	o.Listeners = v
}

// GetProvider returns the Provider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetProvider() string {
	if o == nil || IsNil(o.Provider.Get()) {
		var ret string
		return ret
	}
	return *o.Provider.Get()
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Provider.Get(), o.Provider.IsSet()
}

// HasProvider returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) HasProvider() bool {
	if o != nil && o.Provider.IsSet() {
		return true
	}

	return false
}

// SetProvider gets a reference to the given NullableString and assigns it to the Provider field.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetProvider(v string) {
	o.Provider.Set(&v)
}

// SetProviderNil sets the value for Provider to be an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetProviderNil() {
	o.Provider.Set(nil)
}

// UnsetProvider ensures that no value is present for Provider, not even an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) UnsetProvider() {
	o.Provider.Unset()
}

// GetFlavorId returns the FlavorId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetFlavorId() string {
	if o == nil || IsNil(o.FlavorId.Get()) {
		var ret string
		return ret
	}
	return *o.FlavorId.Get()
}

// GetFlavorIdOk returns a tuple with the FlavorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetFlavorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FlavorId.Get(), o.FlavorId.IsSet()
}

// HasFlavorId returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) HasFlavorId() bool {
	if o != nil && o.FlavorId.IsSet() {
		return true
	}

	return false
}

// SetFlavorId gets a reference to the given NullableString and assigns it to the FlavorId field.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetFlavorId(v string) {
	o.FlavorId.Set(&v)
}

// SetFlavorIdNil sets the value for FlavorId to be an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetFlavorIdNil() {
	o.FlavorId.Set(nil)
}

// UnsetFlavorId ensures that no value is present for FlavorId, not even an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) UnsetFlavorId() {
	o.FlavorId.Unset()
}

// GetAvailabilityZone returns the AvailabilityZone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetAvailabilityZone() AvailabilityZone {
	if o == nil || IsNil(o.AvailabilityZone.Get()) {
		var ret AvailabilityZone
		return ret
	}
	return *o.AvailabilityZone.Get()
}

// GetAvailabilityZoneOk returns a tuple with the AvailabilityZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetAvailabilityZoneOk() (*AvailabilityZone, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvailabilityZone.Get(), o.AvailabilityZone.IsSet()
}

// HasAvailabilityZone returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) HasAvailabilityZone() bool {
	if o != nil && o.AvailabilityZone.IsSet() {
		return true
	}

	return false
}

// SetAvailabilityZone gets a reference to the given NullableAvailabilityZone and assigns it to the AvailabilityZone field.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetAvailabilityZone(v AvailabilityZone) {
	o.AvailabilityZone.Set(&v)
}

// SetAvailabilityZoneNil sets the value for AvailabilityZone to be an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetAvailabilityZoneNil() {
	o.AvailabilityZone.Set(nil)
}

// UnsetAvailabilityZone ensures that no value is present for AvailabilityZone, not even an explicit nil
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) UnsetAvailabilityZone() {
	o.AvailabilityZone.Unset()
}

// GetTargetGroupCount returns the TargetGroupCount field value
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetTargetGroupCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TargetGroupCount
}

// GetTargetGroupCountOk returns a tuple with the TargetGroupCount field value
// and a boolean to check if the value has been set.
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) GetTargetGroupCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetGroupCount, true
}

// SetTargetGroupCount sets field value
func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) SetTargetGroupCount(v int32) {
	o.TargetGroupCount = v
}

func (o BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.ProvisioningStatus.IsSet() {
		toSerialize["provisioning_status"] = o.ProvisioningStatus.Get()
	}
	if o.OperatingStatus.IsSet() {
		toSerialize["operating_status"] = o.OperatingStatus.Get()
	}
	if o.AccessLogs.IsSet() {
		toSerialize["access_logs"] = o.AccessLogs.Get()
	}
	toSerialize["project_id"] = o.ProjectId
	if o.CreatedAt.IsSet() {
		toSerialize["created_at"] = o.CreatedAt.Get()
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updated_at"] = o.UpdatedAt.Get()
	}
	if o.SubnetId.IsSet() {
		toSerialize["subnet_id"] = o.SubnetId.Get()
	}
	if o.Listeners != nil {
		toSerialize["listeners"] = o.Listeners
	}
	if o.Provider.IsSet() {
		toSerialize["provider"] = o.Provider.Get()
	}
	if o.FlavorId.IsSet() {
		toSerialize["flavor_id"] = o.FlavorId.Get()
	}
	if o.AvailabilityZone.IsSet() {
		toSerialize["availability_zone"] = o.AvailabilityZone.Get()
	}
	toSerialize["target_group_count"] = o.TargetGroupCount

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"project_id",
		"target_group_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel := _BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel{}

	err = json.Unmarshal(data, &varBnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel)

	if err != nil {
		return err
	}

	*o = BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel(varBnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "provisioning_status")
		delete(additionalProperties, "operating_status")
		delete(additionalProperties, "access_logs")
		delete(additionalProperties, "project_id")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "subnet_id")
		delete(additionalProperties, "listeners")
		delete(additionalProperties, "provider")
		delete(additionalProperties, "flavor_id")
		delete(additionalProperties, "availability_zone")
		delete(additionalProperties, "target_group_count")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel struct {
	value *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel
	isSet bool
}

func (v NullableBnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) Get() *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel {
	return v.value
}

func (v *NullableBnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) Set(val *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel(val *BnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) *NullableBnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel {
	return &NullableBnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel{value: val, isSet: true}
}

func (v NullableBnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBnsLoadBalancerV1ApiUpdateLoadBalancerModelLoadBalancerModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
