/*
Beyond Networking Service(BNS) Load Balancer API

BNS Load Balancer API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loadbalancer

import (
	"encoding/json"
	"fmt"
)

// checks if the BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel{}

// BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel struct for BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel
type BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel struct {
	// 리스너의 고유 ID
	Id                   string `json:"id"`
	AdditionalProperties map[string]interface{}
}

type _BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel

// NewBnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel instantiates a new BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel(id string) *BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel {
	this := BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel{}
	this.Id = id
	return &this
}

// NewBnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModelWithDefaults instantiates a new BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModelWithDefaults() *BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel {
	this := BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel{}
	return &this
}

// GetId returns the Id field value
func (o *BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel) SetId(v string) {
	o.Id = v
}

func (o BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel := _BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel{}

	err = json.Unmarshal(data, &varBnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel)

	if err != nil {
		return err
	}

	*o = BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel(varBnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel struct {
	value *BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel
	isSet bool
}

func (v NullableBnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel) Get() *BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel {
	return v.value
}

func (v *NullableBnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel) Set(val *BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel(val *BnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel) *NullableBnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel {
	return &NullableBnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel{value: val, isSet: true}
}

func (v NullableBnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBnsLoadBalancerV1ApiUpdateAccessLogModelListenerIdModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
