/*
Beyond Networking Service(BNS) Load Balancer API

BNS Load Balancer API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loadbalancer

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel{}

// BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel struct for BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel
type BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel struct {
	// 헬스 모니터 ID
	Id string `json:"id"`
	// 헬스 모니터 이름
	Name string `json:"name"`
	// 헬스 체크 프로토콜 유형
	Type HealthMonitorType `json:"type"`
	// 헬스 체크 간격 (초)
	Delay int32 `json:"delay"`
	// 응답 대기 시간 (초)
	Timeout int32 `json:"timeout"`
	// 실패로 간주되기 전의 최대 재시도 횟수
	MaxRetries int32 `json:"max_retries"`
	// Down 상태 판정 전 재시도 횟수
	MaxRetriesDown int32                       `json:"max_retries_down"`
	HttpMethod     NullableHealthMonitorMethod `json:"http_method,omitempty"`
	UrlPath        NullableString              `json:"url_path,omitempty"`
	ExpectedCodes  NullableString              `json:"expected_codes,omitempty"`
	// 프로젝트 ID
	ProjectId string `json:"project_id"`
	// 연결된 대상 그룹 목록
	TargetGroups []BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelTargetGroupModel `json:"target_groups"`
	// 프로비저닝 상태
	ProvisioningStatus ProvisioningStatus `json:"provisioning_status"`
	// 운영 상태
	OperatingStatus LoadBalancerOperatingStatus `json:"operating_status"`
	// 리소스가 생성된 시간 <br/> - ISO_8601 형식  <br/> - UTC 기준
	CreatedAt            time.Time                        `json:"created_at"`
	UpdatedAt            NullableTime                     `json:"updated_at,omitempty"`
	HttpVersion          NullableHealthMonitorHttpVersion `json:"http_version,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel

// NewBnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel instantiates a new BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel(id string, name string, type_ HealthMonitorType, delay int32, timeout int32, maxRetries int32, maxRetriesDown int32, projectId string, targetGroups []BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelTargetGroupModel, provisioningStatus ProvisioningStatus, operatingStatus LoadBalancerOperatingStatus, createdAt time.Time) *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel {
	this := BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel{}
	this.Id = id
	this.Name = name
	this.Type = type_
	this.Delay = delay
	this.Timeout = timeout
	this.MaxRetries = maxRetries
	this.MaxRetriesDown = maxRetriesDown
	this.ProjectId = projectId
	this.TargetGroups = targetGroups
	this.ProvisioningStatus = provisioningStatus
	this.OperatingStatus = operatingStatus
	this.CreatedAt = createdAt
	return &this
}

// NewBnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModelWithDefaults instantiates a new BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModelWithDefaults() *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel {
	this := BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel{}
	return &this
}

// GetId returns the Id field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetType() HealthMonitorType {
	if o == nil {
		var ret HealthMonitorType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetTypeOk() (*HealthMonitorType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetType(v HealthMonitorType) {
	o.Type = v
}

// GetDelay returns the Delay field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetDelay() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Delay
}

// GetDelayOk returns a tuple with the Delay field value
// and a boolean to check if the value has been set.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetDelayOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Delay, true
}

// SetDelay sets field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetDelay(v int32) {
	o.Delay = v
}

// GetTimeout returns the Timeout field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetTimeout() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value
// and a boolean to check if the value has been set.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetTimeoutOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timeout, true
}

// SetTimeout sets field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetTimeout(v int32) {
	o.Timeout = v
}

// GetMaxRetries returns the MaxRetries field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetMaxRetries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxRetries
}

// GetMaxRetriesOk returns a tuple with the MaxRetries field value
// and a boolean to check if the value has been set.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetMaxRetriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxRetries, true
}

// SetMaxRetries sets field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetMaxRetries(v int32) {
	o.MaxRetries = v
}

// GetMaxRetriesDown returns the MaxRetriesDown field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetMaxRetriesDown() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxRetriesDown
}

// GetMaxRetriesDownOk returns a tuple with the MaxRetriesDown field value
// and a boolean to check if the value has been set.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetMaxRetriesDownOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxRetriesDown, true
}

// SetMaxRetriesDown sets field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetMaxRetriesDown(v int32) {
	o.MaxRetriesDown = v
}

// GetHttpMethod returns the HttpMethod field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetHttpMethod() HealthMonitorMethod {
	if o == nil || IsNil(o.HttpMethod.Get()) {
		var ret HealthMonitorMethod
		return ret
	}
	return *o.HttpMethod.Get()
}

// GetHttpMethodOk returns a tuple with the HttpMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetHttpMethodOk() (*HealthMonitorMethod, bool) {
	if o == nil {
		return nil, false
	}
	return o.HttpMethod.Get(), o.HttpMethod.IsSet()
}

// HasHttpMethod returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) HasHttpMethod() bool {
	if o != nil && o.HttpMethod.IsSet() {
		return true
	}

	return false
}

// SetHttpMethod gets a reference to the given NullableHealthMonitorMethod and assigns it to the HttpMethod field.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetHttpMethod(v HealthMonitorMethod) {
	o.HttpMethod.Set(&v)
}

// SetHttpMethodNil sets the value for HttpMethod to be an explicit nil
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetHttpMethodNil() {
	o.HttpMethod.Set(nil)
}

// UnsetHttpMethod ensures that no value is present for HttpMethod, not even an explicit nil
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) UnsetHttpMethod() {
	o.HttpMethod.Unset()
}

// GetUrlPath returns the UrlPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetUrlPath() string {
	if o == nil || IsNil(o.UrlPath.Get()) {
		var ret string
		return ret
	}
	return *o.UrlPath.Get()
}

// GetUrlPathOk returns a tuple with the UrlPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetUrlPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UrlPath.Get(), o.UrlPath.IsSet()
}

// HasUrlPath returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) HasUrlPath() bool {
	if o != nil && o.UrlPath.IsSet() {
		return true
	}

	return false
}

// SetUrlPath gets a reference to the given NullableString and assigns it to the UrlPath field.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetUrlPath(v string) {
	o.UrlPath.Set(&v)
}

// SetUrlPathNil sets the value for UrlPath to be an explicit nil
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetUrlPathNil() {
	o.UrlPath.Set(nil)
}

// UnsetUrlPath ensures that no value is present for UrlPath, not even an explicit nil
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) UnsetUrlPath() {
	o.UrlPath.Unset()
}

// GetExpectedCodes returns the ExpectedCodes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetExpectedCodes() string {
	if o == nil || IsNil(o.ExpectedCodes.Get()) {
		var ret string
		return ret
	}
	return *o.ExpectedCodes.Get()
}

// GetExpectedCodesOk returns a tuple with the ExpectedCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetExpectedCodesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpectedCodes.Get(), o.ExpectedCodes.IsSet()
}

// HasExpectedCodes returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) HasExpectedCodes() bool {
	if o != nil && o.ExpectedCodes.IsSet() {
		return true
	}

	return false
}

// SetExpectedCodes gets a reference to the given NullableString and assigns it to the ExpectedCodes field.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetExpectedCodes(v string) {
	o.ExpectedCodes.Set(&v)
}

// SetExpectedCodesNil sets the value for ExpectedCodes to be an explicit nil
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetExpectedCodesNil() {
	o.ExpectedCodes.Set(nil)
}

// UnsetExpectedCodes ensures that no value is present for ExpectedCodes, not even an explicit nil
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) UnsetExpectedCodes() {
	o.ExpectedCodes.Unset()
}

// GetProjectId returns the ProjectId field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetProjectId(v string) {
	o.ProjectId = v
}

// GetTargetGroups returns the TargetGroups field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetTargetGroups() []BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelTargetGroupModel {
	if o == nil {
		var ret []BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelTargetGroupModel
		return ret
	}

	return o.TargetGroups
}

// GetTargetGroupsOk returns a tuple with the TargetGroups field value
// and a boolean to check if the value has been set.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetTargetGroupsOk() ([]BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelTargetGroupModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.TargetGroups, true
}

// SetTargetGroups sets field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetTargetGroups(v []BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelTargetGroupModel) {
	o.TargetGroups = v
}

// GetProvisioningStatus returns the ProvisioningStatus field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetProvisioningStatus() ProvisioningStatus {
	if o == nil {
		var ret ProvisioningStatus
		return ret
	}

	return o.ProvisioningStatus
}

// GetProvisioningStatusOk returns a tuple with the ProvisioningStatus field value
// and a boolean to check if the value has been set.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetProvisioningStatusOk() (*ProvisioningStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProvisioningStatus, true
}

// SetProvisioningStatus sets field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetProvisioningStatus(v ProvisioningStatus) {
	o.ProvisioningStatus = v
}

// GetOperatingStatus returns the OperatingStatus field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetOperatingStatus() LoadBalancerOperatingStatus {
	if o == nil {
		var ret LoadBalancerOperatingStatus
		return ret
	}

	return o.OperatingStatus
}

// GetOperatingStatusOk returns a tuple with the OperatingStatus field value
// and a boolean to check if the value has been set.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetOperatingStatusOk() (*LoadBalancerOperatingStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperatingStatus, true
}

// SetOperatingStatus sets field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetOperatingStatus(v LoadBalancerOperatingStatus) {
	o.OperatingStatus = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}

// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

// GetHttpVersion returns the HttpVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetHttpVersion() HealthMonitorHttpVersion {
	if o == nil || IsNil(o.HttpVersion.Get()) {
		var ret HealthMonitorHttpVersion
		return ret
	}
	return *o.HttpVersion.Get()
}

// GetHttpVersionOk returns a tuple with the HttpVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) GetHttpVersionOk() (*HealthMonitorHttpVersion, bool) {
	if o == nil {
		return nil, false
	}
	return o.HttpVersion.Get(), o.HttpVersion.IsSet()
}

// HasHttpVersion returns a boolean if a field has been set.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) HasHttpVersion() bool {
	if o != nil && o.HttpVersion.IsSet() {
		return true
	}

	return false
}

// SetHttpVersion gets a reference to the given NullableHealthMonitorHttpVersion and assigns it to the HttpVersion field.
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetHttpVersion(v HealthMonitorHttpVersion) {
	o.HttpVersion.Set(&v)
}

// SetHttpVersionNil sets the value for HttpVersion to be an explicit nil
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) SetHttpVersionNil() {
	o.HttpVersion.Set(nil)
}

// UnsetHttpVersion ensures that no value is present for HttpVersion, not even an explicit nil
func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) UnsetHttpVersion() {
	o.HttpVersion.Unset()
}

func (o BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	toSerialize["delay"] = o.Delay
	toSerialize["timeout"] = o.Timeout
	toSerialize["max_retries"] = o.MaxRetries
	toSerialize["max_retries_down"] = o.MaxRetriesDown
	if o.HttpMethod.IsSet() {
		toSerialize["http_method"] = o.HttpMethod.Get()
	}
	if o.UrlPath.IsSet() {
		toSerialize["url_path"] = o.UrlPath.Get()
	}
	if o.ExpectedCodes.IsSet() {
		toSerialize["expected_codes"] = o.ExpectedCodes.Get()
	}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["target_groups"] = o.TargetGroups
	toSerialize["provisioning_status"] = o.ProvisioningStatus
	toSerialize["operating_status"] = o.OperatingStatus
	toSerialize["created_at"] = o.CreatedAt
	if o.UpdatedAt.IsSet() {
		toSerialize["updated_at"] = o.UpdatedAt.Get()
	}
	if o.HttpVersion.IsSet() {
		toSerialize["http_version"] = o.HttpVersion.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"type",
		"delay",
		"timeout",
		"max_retries",
		"max_retries_down",
		"project_id",
		"target_groups",
		"provisioning_status",
		"operating_status",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel := _BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel{}

	err = json.Unmarshal(data, &varBnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel)

	if err != nil {
		return err
	}

	*o = BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel(varBnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "type")
		delete(additionalProperties, "delay")
		delete(additionalProperties, "timeout")
		delete(additionalProperties, "max_retries")
		delete(additionalProperties, "max_retries_down")
		delete(additionalProperties, "http_method")
		delete(additionalProperties, "url_path")
		delete(additionalProperties, "expected_codes")
		delete(additionalProperties, "project_id")
		delete(additionalProperties, "target_groups")
		delete(additionalProperties, "provisioning_status")
		delete(additionalProperties, "operating_status")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "http_version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel struct {
	value *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel
	isSet bool
}

func (v NullableBnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) Get() *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel {
	return v.value
}

func (v *NullableBnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) Set(val *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel(val *BnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) *NullableBnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel {
	return &NullableBnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel{value: val, isSet: true}
}

func (v NullableBnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBnsLoadBalancerV1ApiGetTargetGroupHealthMonitorModelHealthMonitorModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
