/*
Beyond Networking Service(BNS) Load Balancer API

BNS Load Balancer API

API version: 1.3.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loadbalancer

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Member type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Member{}

// Member struct for Member
type Member struct {
	// 대상 인스턴스의 ID
	Id   string         `json:"id"`
	Name NullableString `json:"name,omitempty"`
	// 운영 상태
	OperatingStatus LoadBalancerOperatingStatus `json:"operating_status"`
	// 프로비저닝 상태
	ProvisioningStatus ProvisioningStatus `json:"provisioning_status"`
	// 대상 인스턴스의 IP 주소
	Address string `json:"address"`
	// 대상 인스턴스가 수신하는 포트 번호
	ProtocolPort int32 `json:"protocol_port"`
	// 트래픽 분산 가중치
	Weight int32 `json:"weight"`
	// `true`일 경우 이 인스턴스는 백업 대상으로 설정되며, 주 멤버가 모두 실패했을 때만 사용
	IsBackup bool `json:"is_backup"`
	// 대상 인스턴스가 속한 서브넷의 ID
	SubnetId string `json:"subnet_id"`
	// 해당 멤버 리소스가 속한 프로젝트의 ID
	ProjectId string `json:"project_id"`
	// 리소스가 생성된 시간 <br/> - ISO 8601 형식 <br/> - UTC 기준
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            NullableTime  `json:"updated_at,omitempty"`
	MonitorPort          NullableInt32 `json:"monitor_port,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Member Member

// NewMember instantiates a new Member object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMember(id string, operatingStatus LoadBalancerOperatingStatus, provisioningStatus ProvisioningStatus, address string, protocolPort int32, weight int32, isBackup bool, subnetId string, projectId string, createdAt time.Time) *Member {
	this := Member{}
	this.Id = id
	this.OperatingStatus = operatingStatus
	this.ProvisioningStatus = provisioningStatus
	this.Address = address
	this.ProtocolPort = protocolPort
	this.Weight = weight
	this.IsBackup = isBackup
	this.SubnetId = subnetId
	this.ProjectId = projectId
	this.CreatedAt = createdAt
	return &this
}

// NewMemberWithDefaults instantiates a new Member object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemberWithDefaults() *Member {
	this := Member{}
	return &this
}

// GetId returns the Id field value
func (o *Member) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Member) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Member) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Member) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Member) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *Member) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *Member) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *Member) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *Member) UnsetName() {
	o.Name.Unset()
}

// GetOperatingStatus returns the OperatingStatus field value
func (o *Member) GetOperatingStatus() LoadBalancerOperatingStatus {
	if o == nil {
		var ret LoadBalancerOperatingStatus
		return ret
	}

	return o.OperatingStatus
}

// GetOperatingStatusOk returns a tuple with the OperatingStatus field value
// and a boolean to check if the value has been set.
func (o *Member) GetOperatingStatusOk() (*LoadBalancerOperatingStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperatingStatus, true
}

// SetOperatingStatus sets field value
func (o *Member) SetOperatingStatus(v LoadBalancerOperatingStatus) {
	o.OperatingStatus = v
}

// GetProvisioningStatus returns the ProvisioningStatus field value
func (o *Member) GetProvisioningStatus() ProvisioningStatus {
	if o == nil {
		var ret ProvisioningStatus
		return ret
	}

	return o.ProvisioningStatus
}

// GetProvisioningStatusOk returns a tuple with the ProvisioningStatus field value
// and a boolean to check if the value has been set.
func (o *Member) GetProvisioningStatusOk() (*ProvisioningStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProvisioningStatus, true
}

// SetProvisioningStatus sets field value
func (o *Member) SetProvisioningStatus(v ProvisioningStatus) {
	o.ProvisioningStatus = v
}

// GetAddress returns the Address field value
func (o *Member) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *Member) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *Member) SetAddress(v string) {
	o.Address = v
}

// GetProtocolPort returns the ProtocolPort field value
func (o *Member) GetProtocolPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProtocolPort
}

// GetProtocolPortOk returns a tuple with the ProtocolPort field value
// and a boolean to check if the value has been set.
func (o *Member) GetProtocolPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProtocolPort, true
}

// SetProtocolPort sets field value
func (o *Member) SetProtocolPort(v int32) {
	o.ProtocolPort = v
}

// GetWeight returns the Weight field value
func (o *Member) GetWeight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Weight
}

// GetWeightOk returns a tuple with the Weight field value
// and a boolean to check if the value has been set.
func (o *Member) GetWeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Weight, true
}

// SetWeight sets field value
func (o *Member) SetWeight(v int32) {
	o.Weight = v
}

// GetIsBackup returns the IsBackup field value
func (o *Member) GetIsBackup() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsBackup
}

// GetIsBackupOk returns a tuple with the IsBackup field value
// and a boolean to check if the value has been set.
func (o *Member) GetIsBackupOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsBackup, true
}

// SetIsBackup sets field value
func (o *Member) SetIsBackup(v bool) {
	o.IsBackup = v
}

// GetSubnetId returns the SubnetId field value
func (o *Member) GetSubnetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubnetId
}

// GetSubnetIdOk returns a tuple with the SubnetId field value
// and a boolean to check if the value has been set.
func (o *Member) GetSubnetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubnetId, true
}

// SetSubnetId sets field value
func (o *Member) SetSubnetId(v string) {
	o.SubnetId = v
}

// GetProjectId returns the ProjectId field value
func (o *Member) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *Member) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *Member) SetProjectId(v string) {
	o.ProjectId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Member) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Member) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Member) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Member) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Member) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Member) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *Member) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}

// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *Member) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *Member) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

// GetMonitorPort returns the MonitorPort field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Member) GetMonitorPort() int32 {
	if o == nil || IsNil(o.MonitorPort.Get()) {
		var ret int32
		return ret
	}
	return *o.MonitorPort.Get()
}

// GetMonitorPortOk returns a tuple with the MonitorPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Member) GetMonitorPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MonitorPort.Get(), o.MonitorPort.IsSet()
}

// HasMonitorPort returns a boolean if a field has been set.
func (o *Member) HasMonitorPort() bool {
	if o != nil && o.MonitorPort.IsSet() {
		return true
	}

	return false
}

// SetMonitorPort gets a reference to the given NullableInt32 and assigns it to the MonitorPort field.
func (o *Member) SetMonitorPort(v int32) {
	o.MonitorPort.Set(&v)
}

// SetMonitorPortNil sets the value for MonitorPort to be an explicit nil
func (o *Member) SetMonitorPortNil() {
	o.MonitorPort.Set(nil)
}

// UnsetMonitorPort ensures that no value is present for MonitorPort, not even an explicit nil
func (o *Member) UnsetMonitorPort() {
	o.MonitorPort.Unset()
}

func (o Member) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Member) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	toSerialize["operating_status"] = o.OperatingStatus
	toSerialize["provisioning_status"] = o.ProvisioningStatus
	toSerialize["address"] = o.Address
	toSerialize["protocol_port"] = o.ProtocolPort
	toSerialize["weight"] = o.Weight
	toSerialize["is_backup"] = o.IsBackup
	toSerialize["subnet_id"] = o.SubnetId
	toSerialize["project_id"] = o.ProjectId
	toSerialize["created_at"] = o.CreatedAt
	if o.UpdatedAt.IsSet() {
		toSerialize["updated_at"] = o.UpdatedAt.Get()
	}
	if o.MonitorPort.IsSet() {
		toSerialize["monitor_port"] = o.MonitorPort.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Member) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"operating_status",
		"provisioning_status",
		"address",
		"protocol_port",
		"weight",
		"is_backup",
		"subnet_id",
		"project_id",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMember := _Member{}

	err = json.Unmarshal(data, &varMember)

	if err != nil {
		return err
	}

	*o = Member(varMember)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "operating_status")
		delete(additionalProperties, "provisioning_status")
		delete(additionalProperties, "address")
		delete(additionalProperties, "protocol_port")
		delete(additionalProperties, "weight")
		delete(additionalProperties, "is_backup")
		delete(additionalProperties, "subnet_id")
		delete(additionalProperties, "project_id")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "monitor_port")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMember struct {
	value *Member
	isSet bool
}

func (v NullableMember) Get() *Member {
	return v.value
}

func (v *NullableMember) Set(val *Member) {
	v.value = val
	v.isSet = true
}

func (v NullableMember) IsSet() bool {
	return v.isSet
}

func (v *NullableMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMember(val *Member) *NullableMember {
	return &NullableMember{value: val, isSet: true}
}

func (v NullableMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
