/*
Beyond Networking Service(BNS) Load Balancer API

BNS Load Balancer API

API version: 1.3.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loadbalancer

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdatedListener type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatedListener{}

// UpdatedListener struct for UpdatedListener
type UpdatedListener struct {
	// 멤버(서버)의 ID
	Id                   string `json:"id"`
	AdditionalProperties map[string]interface{}
}

type _UpdatedListener UpdatedListener

// NewUpdatedListener instantiates a new UpdatedListener object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatedListener(id string) *UpdatedListener {
	this := UpdatedListener{}
	this.Id = id
	return &this
}

// NewUpdatedListenerWithDefaults instantiates a new UpdatedListener object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatedListenerWithDefaults() *UpdatedListener {
	this := UpdatedListener{}
	return &this
}

// GetId returns the Id field value
func (o *UpdatedListener) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdatedListener) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdatedListener) SetId(v string) {
	o.Id = v
}

func (o UpdatedListener) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatedListener) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdatedListener) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatedListener := _UpdatedListener{}

	err = json.Unmarshal(data, &varUpdatedListener)

	if err != nil {
		return err
	}

	*o = UpdatedListener(varUpdatedListener)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdatedListener struct {
	value *UpdatedListener
	isSet bool
}

func (v NullableUpdatedListener) Get() *UpdatedListener {
	return v.value
}

func (v *NullableUpdatedListener) Set(val *UpdatedListener) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatedListener) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatedListener) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatedListener(val *UpdatedListener) *NullableUpdatedListener {
	return &NullableUpdatedListener{value: val, isSet: true}
}

func (v NullableUpdatedListener) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatedListener) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
