site_name: kc-sdk-go/v2/loadbalancer (POC)
docs_dir: docs_src
site_dir: site
theme:
  name: material
  palette:
    scheme: default
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
nav:
  - Getting Started: index.md
  - API:
      - HealthMonitorAPI.md: api/HealthMonitorAPI.md
      - HighAvailabilityGroupAPI.md: api/HighAvailabilityGroupAPI.md
      - L7PolicyAPI.md: api/L7PolicyAPI.md
      - L7RuleAPI.md: api/L7RuleAPI.md
      - ListenerAPI.md: api/ListenerAPI.md
      - LoadBalancerAPI.md: api/LoadBalancerAPI.md
      - TargetGroupAPI.md: api/TargetGroupAPI.md
  - Models:
      - AccessLog: models/AccessLog.md
      - AddL7PolicyRule: models/AddL7PolicyRule.md
      - AddL7PolicyRuleRequest: models/AddL7PolicyRuleRequest.md
      - AddL7PolicyRuleResponse: models/AddL7PolicyRuleResponse.md
      - AddTarget: models/AddTarget.md
      - AddTargetRequest: models/AddTargetRequest.md
      - AddTargetResponse: models/AddTargetResponse.md
      - AssociateNewPublicIpResponse: models/AssociateNewPublicIpResponse.md
      - AssociatePublicIpResponse: models/AssociatePublicIpResponse.md
      - AvailabilityZone: models/AvailabilityZone.md
      - AvailabilityZoneInfo: models/AvailabilityZoneInfo.md
      - BeyondLoadBalancer: models/BeyondLoadBalancer.md
      - BeyondLoadBalancerResult: models/BeyondLoadBalancerResult.md
      - BeyondLoadBalancerScheme: models/BeyondLoadBalancerScheme.md
      - ContentTypesDto: models/ContentTypesDto.md
      - CreatedL7Policy2: models/CreatedL7Policy2.md
      - CreatedListener: models/CreatedListener.md
      - CreatedLoadBalancer: models/CreatedLoadBalancer.md
      - CreatedMember: models/CreatedMember.md
      - CreatedPool: models/CreatedPool.md
      - CreateHaGroup: models/CreateHaGroup.md
      - CreateHaGroupRequest: models/CreateHaGroupRequest.md
      - CreateHaGroupResponse: models/CreateHaGroupResponse.md
      - CreateHealthMonitor: models/CreateHealthMonitor.md
      - CreateHealthMonitorRequest: models/CreateHealthMonitorRequest.md
      - CreateHealthMonitorResponse: models/CreateHealthMonitorResponse.md
      - CreateL7Policy: models/CreateL7Policy.md
      - CreateL7PolicyRequest: models/CreateL7PolicyRequest.md
      - CreateL7PolicyResponse: models/CreateL7PolicyResponse.md
      - CreateListener: models/CreateListener.md
      - CreateListenerRequest: models/CreateListenerRequest.md
      - CreateListenerResponse: models/CreateListenerResponse.md
      - CreateLoadBalancer: models/CreateLoadBalancer.md
      - CreateLoadBalancerHealthMonitorRequest: models/CreateLoadBalancerHealthMonitorRequest.md
      - CreateLoadBalancerL7PolicyRequest: models/CreateLoadBalancerL7PolicyRequest.md
      - CreateLoadBalancerListenerRequest: models/CreateLoadBalancerListenerRequest.md
      - CreateLoadBalancerMemberRequest: models/CreateLoadBalancerMemberRequest.md
      - CreateLoadBalancerPoolRequest: models/CreateLoadBalancerPoolRequest.md
      - CreateLoadBalancerRequest: models/CreateLoadBalancerRequest.md
      - CreateLoadBalancerResponse: models/CreateLoadBalancerResponse.md
      - CreateTargetGroup: models/CreateTargetGroup.md
      - CreateTargetGroupRequest: models/CreateTargetGroupRequest.md
      - CreateTargetGroupResponse: models/CreateTargetGroupResponse.md
      - ErrorResponse: models/ErrorResponse.md
      - ErrorResponseSub: models/ErrorResponseSub.md
      - Flavor: models/Flavor.md
      - GetHaGroupResponse: models/GetHaGroupResponse.md
      - GetL7PolicyResponse: models/GetL7PolicyResponse.md
      - GetL7PolicyRuleResponse: models/GetL7PolicyRuleResponse.md
      - GetListenerResponse: models/GetListenerResponse.md
      - GetLoadBalancerResponse: models/GetLoadBalancerResponse.md
      - GetTargetGroupHealthCheckSubnetsResponse: models/GetTargetGroupHealthCheckSubnetsResponse.md
      - GetTargetGroupHealthMonitorResponse: models/GetTargetGroupHealthMonitorResponse.md
      - GetTargetGroupResponse: models/GetTargetGroupResponse.md
      - GetTargetResponse: models/GetTargetResponse.md
      - HealthMonitor: models/HealthMonitor.md
      - HealthMonitorHttpVersion: models/HealthMonitorHttpVersion.md
      - HealthMonitorMethod: models/HealthMonitorMethod.md
      - HealthMonitorType: models/HealthMonitorType.md
      - Ids: models/Ids.md
      - InsertHeaderRequest: models/InsertHeaderRequest.md
      - L7Policy: models/L7Policy.md
      - L7PolicyAction: models/L7PolicyAction.md
      - L7PolicyResult: models/L7PolicyResult.md
      - L7RuleCompareType: models/L7RuleCompareType.md
      - L7RuleType: models/L7RuleType.md
      - ListAvailabilityZonesResponse: models/ListAvailabilityZonesResponse.md
      - Listener: models/Listener.md
      - ListenerResult: models/ListenerResult.md
      - ListHaGroupsResponse: models/ListHaGroupsResponse.md
      - ListL7PoliciesResponse: models/ListL7PoliciesResponse.md
      - ListL7PolicyRulesResponse: models/ListL7PolicyRulesResponse.md
      - ListListenersResponse: models/ListListenersResponse.md
      - ListLoadBalancersResponse: models/ListLoadBalancersResponse.md
      - ListLoadBalancerTypesResponse: models/ListLoadBalancerTypesResponse.md
      - ListTargetGroupsResponse: models/ListTargetGroupsResponse.md
      - ListTargetsInTargetGroupResponse: models/ListTargetsInTargetGroupResponse.md
      - ListTlsCertificatesResponse: models/ListTlsCertificatesResponse.md
      - ListTlsCertificatesSecret: models/ListTlsCertificatesSecret.md
      - LoadBalancer: models/LoadBalancer.md
      - LoadBalancerAlpnProtocol: models/LoadBalancerAlpnProtocol.md
      - LoadBalancerDetail: models/LoadBalancerDetail.md
      - LoadBalancerListener: models/LoadBalancerListener.md
      - LoadBalancerListenerInsertHeadersValue: models/LoadBalancerListenerInsertHeadersValue.md
      - LoadBalancerOperatingStatus: models/LoadBalancerOperatingStatus.md
      - LoadBalancerPool: models/LoadBalancerPool.md
      - LoadBalancerPoolAlgorithm: models/LoadBalancerPoolAlgorithm.md
      - LoadBalancerPoolProtocol: models/LoadBalancerPoolProtocol.md
      - LoadBalancerResult: models/LoadBalancerResult.md
      - LoadBalancerSessionPersistenceType: models/LoadBalancerSessionPersistenceType.md
      - LoadBalancerType: models/LoadBalancerType.md
      - Member: models/Member.md
      - MemberResult: models/MemberResult.md
      - Pool: models/Pool.md
      - PoolMember: models/PoolMember.md
      - PoolRefRequest: models/PoolRefRequest.md
      - Protocol: models/Protocol.md
      - ProvisioningStatus: models/ProvisioningStatus.md
      - PublicIp: models/PublicIp.md
      - RemovePublicIpResponse: models/RemovePublicIpResponse.md
      - Rule: models/Rule.md
      - RuleResult: models/RuleResult.md
      - Secret: models/Secret.md
      - SecurityGroup: models/SecurityGroup.md
      - SessionPersistence: models/SessionPersistence.md
      - SessionPersistenceRequest: models/SessionPersistenceRequest.md
      - Subnet: models/Subnet.md
      - TargetGroup: models/TargetGroup.md
      - TargetGroupHealthMonitor: models/TargetGroupHealthMonitor.md
      - TLSVersion: models/TLSVersion.md
      - UpdateAccessLog: models/UpdateAccessLog.md
      - UpdateAccessLogRequest: models/UpdateAccessLogRequest.md
      - UpdateAccessLogResponse: models/UpdateAccessLogResponse.md
      - UpdatedL7Policy: models/UpdatedL7Policy.md
      - UpdatedListener: models/UpdatedListener.md
      - UpdatedLoadBalancer: models/UpdatedLoadBalancer.md
      - UpdatedRule: models/UpdatedRule.md
      - UpdateHaGroup: models/UpdateHaGroup.md
      - UpdateHaGroupLoadBalancer: models/UpdateHaGroupLoadBalancer.md
      - UpdateHaGroupLoadBalancerRequest: models/UpdateHaGroupLoadBalancerRequest.md
      - UpdateHaGroupLoadBalancerResponse: models/UpdateHaGroupLoadBalancerResponse.md
      - UpdateHaGroupRequest: models/UpdateHaGroupRequest.md
      - UpdateHaGroupResponse: models/UpdateHaGroupResponse.md
      - UpdateHealthMonitor: models/UpdateHealthMonitor.md
      - UpdateHealthMonitorRequest: models/UpdateHealthMonitorRequest.md
      - UpdateHealthMonitorResponse: models/UpdateHealthMonitorResponse.md
      - UpdateL7Policy: models/UpdateL7Policy.md
      - UpdateL7PolicyRequest: models/UpdateL7PolicyRequest.md
      - UpdateL7PolicyResponse: models/UpdateL7PolicyResponse.md
      - UpdateL7PolicyRule: models/UpdateL7PolicyRule.md
      - UpdateL7PolicyRuleRequest: models/UpdateL7PolicyRuleRequest.md
      - UpdateL7PolicyRuleResponse: models/UpdateL7PolicyRuleResponse.md
      - UpdateListener: models/UpdateListener.md
      - UpdateListenerRequest: models/UpdateListenerRequest.md
      - UpdateListenerResponse: models/UpdateListenerResponse.md
      - UpdateLoadBalancer: models/UpdateLoadBalancer.md
      - UpdateLoadBalancerRequest: models/UpdateLoadBalancerRequest.md
      - UpdateLoadBalancerResponse: models/UpdateLoadBalancerResponse.md
      - UpdateTarget: models/UpdateTarget.md
      - UpdateTargetGroup: models/UpdateTargetGroup.md
      - UpdateTargetGroupRequest: models/UpdateTargetGroupRequest.md
      - UpdateTargetGroupResponse: models/UpdateTargetGroupResponse.md
      - UpdateTargetRequest: models/UpdateTargetRequest.md
      - UpdateTargetResponse: models/UpdateTargetResponse.md
      - UpdateTargets: models/UpdateTargets.md
      - UpdateTargetsRequest: models/UpdateTargetsRequest.md
      - VpcSubnet: models/VpcSubnet.md
      - VpcSubnetRequest: models/VpcSubnetRequest.md
      - XForwardedFor: models/XForwardedFor.md
      - XForwardedProto: models/XForwardedProto.md
