/*
kms API

kms API

API version: 1.3.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kms

import (
	"encoding/json"
	"fmt"
)

// checks if the DeactivateKeyVersionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeactivateKeyVersionResponse{}

// DeactivateKeyVersionResponse struct for DeactivateKeyVersionResponse
type DeactivateKeyVersionResponse struct {
	// 키 버전
	Version              DeactivateKeyVersionVersion `json:"version"`
	AdditionalProperties map[string]interface{}
}

type _DeactivateKeyVersionResponse DeactivateKeyVersionResponse

// NewDeactivateKeyVersionResponse instantiates a new DeactivateKeyVersionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeactivateKeyVersionResponse(version DeactivateKeyVersionVersion) *DeactivateKeyVersionResponse {
	this := DeactivateKeyVersionResponse{}
	this.Version = version
	return &this
}

// NewDeactivateKeyVersionResponseWithDefaults instantiates a new DeactivateKeyVersionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeactivateKeyVersionResponseWithDefaults() *DeactivateKeyVersionResponse {
	this := DeactivateKeyVersionResponse{}
	return &this
}

// GetVersion returns the Version field value
func (o *DeactivateKeyVersionResponse) GetVersion() DeactivateKeyVersionVersion {
	if o == nil {
		var ret DeactivateKeyVersionVersion
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *DeactivateKeyVersionResponse) GetVersionOk() (*DeactivateKeyVersionVersion, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *DeactivateKeyVersionResponse) SetVersion(v DeactivateKeyVersionVersion) {
	o.Version = v
}

func (o DeactivateKeyVersionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeactivateKeyVersionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeactivateKeyVersionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeactivateKeyVersionResponse := _DeactivateKeyVersionResponse{}

	err = json.Unmarshal(data, &varDeactivateKeyVersionResponse)

	if err != nil {
		return err
	}

	*o = DeactivateKeyVersionResponse(varDeactivateKeyVersionResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeactivateKeyVersionResponse struct {
	value *DeactivateKeyVersionResponse
	isSet bool
}

func (v NullableDeactivateKeyVersionResponse) Get() *DeactivateKeyVersionResponse {
	return v.value
}

func (v *NullableDeactivateKeyVersionResponse) Set(val *DeactivateKeyVersionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeactivateKeyVersionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeactivateKeyVersionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeactivateKeyVersionResponse(val *DeactivateKeyVersionResponse) *NullableDeactivateKeyVersionResponse {
	return &NullableDeactivateKeyVersionResponse{value: val, isSet: true}
}

func (v NullableDeactivateKeyVersionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeactivateKeyVersionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
