/*
kms API

kms API

API version: 1.3.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kms

import (
	"encoding/json"
	"fmt"
)

// checks if the BulkCancelScheduledKeyVersionDestructionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkCancelScheduledKeyVersionDestructionResponse{}

// BulkCancelScheduledKeyVersionDestructionResponse struct for BulkCancelScheduledKeyVersionDestructionResponse
type BulkCancelScheduledKeyVersionDestructionResponse struct {
	// 키 버전별 처리 결과
	Versions             Result `json:"versions"`
	AdditionalProperties map[string]interface{}
}

type _BulkCancelScheduledKeyVersionDestructionResponse BulkCancelScheduledKeyVersionDestructionResponse

// NewBulkCancelScheduledKeyVersionDestructionResponse instantiates a new BulkCancelScheduledKeyVersionDestructionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkCancelScheduledKeyVersionDestructionResponse(versions Result) *BulkCancelScheduledKeyVersionDestructionResponse {
	this := BulkCancelScheduledKeyVersionDestructionResponse{}
	this.Versions = versions
	return &this
}

// NewBulkCancelScheduledKeyVersionDestructionResponseWithDefaults instantiates a new BulkCancelScheduledKeyVersionDestructionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkCancelScheduledKeyVersionDestructionResponseWithDefaults() *BulkCancelScheduledKeyVersionDestructionResponse {
	this := BulkCancelScheduledKeyVersionDestructionResponse{}
	return &this
}

// GetVersions returns the Versions field value
func (o *BulkCancelScheduledKeyVersionDestructionResponse) GetVersions() Result {
	if o == nil {
		var ret Result
		return ret
	}

	return o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value
// and a boolean to check if the value has been set.
func (o *BulkCancelScheduledKeyVersionDestructionResponse) GetVersionsOk() (*Result, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Versions, true
}

// SetVersions sets field value
func (o *BulkCancelScheduledKeyVersionDestructionResponse) SetVersions(v Result) {
	o.Versions = v
}

func (o BulkCancelScheduledKeyVersionDestructionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkCancelScheduledKeyVersionDestructionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["versions"] = o.Versions

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BulkCancelScheduledKeyVersionDestructionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"versions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkCancelScheduledKeyVersionDestructionResponse := _BulkCancelScheduledKeyVersionDestructionResponse{}

	err = json.Unmarshal(data, &varBulkCancelScheduledKeyVersionDestructionResponse)

	if err != nil {
		return err
	}

	*o = BulkCancelScheduledKeyVersionDestructionResponse(varBulkCancelScheduledKeyVersionDestructionResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "versions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBulkCancelScheduledKeyVersionDestructionResponse struct {
	value *BulkCancelScheduledKeyVersionDestructionResponse
	isSet bool
}

func (v NullableBulkCancelScheduledKeyVersionDestructionResponse) Get() *BulkCancelScheduledKeyVersionDestructionResponse {
	return v.value
}

func (v *NullableBulkCancelScheduledKeyVersionDestructionResponse) Set(val *BulkCancelScheduledKeyVersionDestructionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkCancelScheduledKeyVersionDestructionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkCancelScheduledKeyVersionDestructionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkCancelScheduledKeyVersionDestructionResponse(val *BulkCancelScheduledKeyVersionDestructionResponse) *NullableBulkCancelScheduledKeyVersionDestructionResponse {
	return &NullableBulkCancelScheduledKeyVersionDestructionResponse{value: val, isSet: true}
}

func (v NullableBulkCancelScheduledKeyVersionDestructionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkCancelScheduledKeyVersionDestructionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
