/*
kms API

kms API

API version: 1.3.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kms

import (
	"encoding/json"
	"fmt"
)

// checks if the VerifySignature type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifySignature{}

// VerifySignature struct for VerifySignature
type VerifySignature struct {
	// 서명을 검증할 원본 데이터
	Input string `json:"input"`
	// 검증할 전자 서명 <br/> - [Sign data](/openapi/security/kms/sign-data) 응답에서 확인
	Output               string `json:"output"`
	AdditionalProperties map[string]interface{}
}

type _VerifySignature VerifySignature

// NewVerifySignature instantiates a new VerifySignature object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifySignature(input string, output string) *VerifySignature {
	this := VerifySignature{}
	this.Input = input
	this.Output = output
	return &this
}

// NewVerifySignatureWithDefaults instantiates a new VerifySignature object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifySignatureWithDefaults() *VerifySignature {
	this := VerifySignature{}
	return &this
}

// GetInput returns the Input field value
func (o *VerifySignature) GetInput() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *VerifySignature) GetInputOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Input, true
}

// SetInput sets field value
func (o *VerifySignature) SetInput(v string) {
	o.Input = v
}

// GetOutput returns the Output field value
func (o *VerifySignature) GetOutput() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Output
}

// GetOutputOk returns a tuple with the Output field value
// and a boolean to check if the value has been set.
func (o *VerifySignature) GetOutputOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Output, true
}

// SetOutput sets field value
func (o *VerifySignature) SetOutput(v string) {
	o.Output = v
}

func (o VerifySignature) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifySignature) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["input"] = o.Input
	toSerialize["output"] = o.Output

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VerifySignature) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"input",
		"output",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifySignature := _VerifySignature{}

	err = json.Unmarshal(data, &varVerifySignature)

	if err != nil {
		return err
	}

	*o = VerifySignature(varVerifySignature)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "input")
		delete(additionalProperties, "output")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVerifySignature struct {
	value *VerifySignature
	isSet bool
}

func (v NullableVerifySignature) Get() *VerifySignature {
	return v.value
}

func (v *NullableVerifySignature) Set(val *VerifySignature) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifySignature) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifySignature) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifySignature(val *VerifySignature) *NullableVerifySignature {
	return &NullableVerifySignature{value: val, isSet: true}
}

func (v NullableVerifySignature) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifySignature) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
