/*
Beyond Compute Service(BCS) API

Beyond Compute Service API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bcs

import (
	"encoding/json"
	"fmt"
)

// checks if the BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel{}

// BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel struct for BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel
type BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel struct {
	NetworkInterface     BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelInstanceNetworkInterfaceModel `json:"network_interface"`
	AdditionalProperties map[string]interface{}
}

type _BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel

// NewBcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel instantiates a new BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel(networkInterface BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelInstanceNetworkInterfaceModel) *BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel {
	this := BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel{}
	this.NetworkInterface = networkInterface
	return &this
}

// NewBcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModelWithDefaults instantiates a new BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModelWithDefaults() *BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel {
	this := BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel{}
	return &this
}

// GetNetworkInterface returns the NetworkInterface field value
func (o *BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel) GetNetworkInterface() BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelInstanceNetworkInterfaceModel {
	if o == nil {
		var ret BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelInstanceNetworkInterfaceModel
		return ret
	}

	return o.NetworkInterface
}

// GetNetworkInterfaceOk returns a tuple with the NetworkInterface field value
// and a boolean to check if the value has been set.
func (o *BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel) GetNetworkInterfaceOk() (*BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelInstanceNetworkInterfaceModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkInterface, true
}

// SetNetworkInterface sets field value
func (o *BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel) SetNetworkInterface(v BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelInstanceNetworkInterfaceModel) {
	o.NetworkInterface = v
}

func (o BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["network_interface"] = o.NetworkInterface

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"network_interface",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel := _BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel{}

	err = json.Unmarshal(data, &varBcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel)

	if err != nil {
		return err
	}

	*o = BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel(varBcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "network_interface")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel struct {
	value *BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel
	isSet bool
}

func (v NullableBcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel) Get() *BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel {
	return v.value
}

func (v *NullableBcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel) Set(val *BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel(val *BcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel) *NullableBcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel {
	return &NullableBcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel{value: val, isSet: true}
}

func (v NullableBcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBcsInstanceV1ApiUpdateNetworkInterfaceAllowedAddressesModelResponseInstanceNetworkInterfaceModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
