/*
Beyond Compute Service(BCS) API

Beyond Compute Service API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bcs

import (
	"encoding/json"
	"fmt"
)

// checks if the BodyCreateInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BodyCreateInstance{}

// BodyCreateInstance struct for BodyCreateInstance
type BodyCreateInstance struct {
	Instance             CreateInstanceModel `json:"instance"`
	AdditionalProperties map[string]interface{}
}

type _BodyCreateInstance BodyCreateInstance

// NewBodyCreateInstance instantiates a new BodyCreateInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBodyCreateInstance(instance CreateInstanceModel) *BodyCreateInstance {
	this := BodyCreateInstance{}
	this.Instance = instance
	return &this
}

// NewBodyCreateInstanceWithDefaults instantiates a new BodyCreateInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBodyCreateInstanceWithDefaults() *BodyCreateInstance {
	this := BodyCreateInstance{}
	return &this
}

// GetInstance returns the Instance field value
func (o *BodyCreateInstance) GetInstance() CreateInstanceModel {
	if o == nil {
		var ret CreateInstanceModel
		return ret
	}

	return o.Instance
}

// GetInstanceOk returns a tuple with the Instance field value
// and a boolean to check if the value has been set.
func (o *BodyCreateInstance) GetInstanceOk() (*CreateInstanceModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Instance, true
}

// SetInstance sets field value
func (o *BodyCreateInstance) SetInstance(v CreateInstanceModel) {
	o.Instance = v
}

func (o BodyCreateInstance) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BodyCreateInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["instance"] = o.Instance

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BodyCreateInstance) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"instance",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBodyCreateInstance := _BodyCreateInstance{}

	err = json.Unmarshal(data, &varBodyCreateInstance)

	if err != nil {
		return err
	}

	*o = BodyCreateInstance(varBodyCreateInstance)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "instance")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBodyCreateInstance struct {
	value *BodyCreateInstance
	isSet bool
}

func (v NullableBodyCreateInstance) Get() *BodyCreateInstance {
	return v.value
}

func (v *NullableBodyCreateInstance) Set(val *BodyCreateInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableBodyCreateInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableBodyCreateInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBodyCreateInstance(val *BodyCreateInstance) *NullableBodyCreateInstance {
	return &NullableBodyCreateInstance{value: val, isSet: true}
}

func (v NullableBodyCreateInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBodyCreateInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
