/*
Beyond Compute Service(BCS) API

Beyond Compute Service API

API version: 1.2.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bcs

import (
	"encoding/json"
)

// checks if the UpdateInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateInstance{}

// UpdateInstance struct for UpdateInstance
type UpdateInstance struct {
	Name                 NullableString `json:"name,omitempty"`
	Description          NullableString `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateInstance UpdateInstance

// NewUpdateInstance instantiates a new UpdateInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateInstance() *UpdateInstance {
	this := UpdateInstance{}
	return &this
}

// NewUpdateInstanceWithDefaults instantiates a new UpdateInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateInstanceWithDefaults() *UpdateInstance {
	this := UpdateInstance{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateInstance) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateInstance) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *UpdateInstance) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *UpdateInstance) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *UpdateInstance) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *UpdateInstance) UnsetName() {
	o.Name.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateInstance) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateInstance) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateInstance) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *UpdateInstance) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *UpdateInstance) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *UpdateInstance) UnsetDescription() {
	o.Description.Unset()
}

func (o UpdateInstance) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateInstance) UnmarshalJSON(data []byte) (err error) {
	varUpdateInstance := _UpdateInstance{}

	err = json.Unmarshal(data, &varUpdateInstance)

	if err != nil {
		return err
	}

	*o = UpdateInstance(varUpdateInstance)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateInstance struct {
	value *UpdateInstance
	isSet bool
}

func (v NullableUpdateInstance) Get() *UpdateInstance {
	return v.value
}

func (v *NullableUpdateInstance) Set(val *UpdateInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateInstance(val *UpdateInstance) *NullableUpdateInstance {
	return &NullableUpdateInstance{value: val, isSet: true}
}

func (v NullableUpdateInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
