/*
Beyond Compute Service(BCS) API

Beyond Compute Service API

API version: 1.2.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bcs

import (
	"encoding/json"
	"time"
)

// checks if the UpdatedNetworkInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatedNetworkInterface{}

// UpdatedNetworkInterface struct for UpdatedNetworkInterface
type UpdatedNetworkInterface struct {
	Id                                NullableString `json:"id,omitempty"`
	Name                              NullableString `json:"name,omitempty"`
	Status                            NullableString `json:"status,omitempty"`
	Description                       NullableString `json:"description,omitempty"`
	ProjectId                         NullableString `json:"project_id,omitempty"`
	IsNetworkInterfaceSecurityEnabled NullableBool   `json:"is_network_interface_security_enabled,omitempty"`
	SecurityGroups                    []string       `json:"security_groups,omitempty"`
	MacAddress                        NullableString `json:"mac_address,omitempty"`
	DeviceId                          NullableString `json:"device_id,omitempty"`
	SecondaryIps                      []string       `json:"secondary_ips,omitempty"`
	CreatedAt                         NullableTime   `json:"created_at,omitempty"`
	UpdatedAt                         NullableTime   `json:"updated_at,omitempty"`
	PrivateIp                         NullableString `json:"private_ip,omitempty"`
	AdditionalProperties              map[string]interface{}
}

type _UpdatedNetworkInterface UpdatedNetworkInterface

// NewUpdatedNetworkInterface instantiates a new UpdatedNetworkInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatedNetworkInterface() *UpdatedNetworkInterface {
	this := UpdatedNetworkInterface{}
	return &this
}

// NewUpdatedNetworkInterfaceWithDefaults instantiates a new UpdatedNetworkInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatedNetworkInterfaceWithDefaults() *UpdatedNetworkInterface {
	this := UpdatedNetworkInterface{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatedNetworkInterface) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatedNetworkInterface) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *UpdatedNetworkInterface) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *UpdatedNetworkInterface) SetId(v string) {
	o.Id.Set(&v)
}

// SetIdNil sets the value for Id to be an explicit nil
func (o *UpdatedNetworkInterface) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *UpdatedNetworkInterface) UnsetId() {
	o.Id.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatedNetworkInterface) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatedNetworkInterface) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *UpdatedNetworkInterface) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *UpdatedNetworkInterface) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *UpdatedNetworkInterface) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *UpdatedNetworkInterface) UnsetName() {
	o.Name.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatedNetworkInterface) GetStatus() string {
	if o == nil || IsNil(o.Status.Get()) {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatedNetworkInterface) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *UpdatedNetworkInterface) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *UpdatedNetworkInterface) SetStatus(v string) {
	o.Status.Set(&v)
}

// SetStatusNil sets the value for Status to be an explicit nil
func (o *UpdatedNetworkInterface) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *UpdatedNetworkInterface) UnsetStatus() {
	o.Status.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatedNetworkInterface) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatedNetworkInterface) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdatedNetworkInterface) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *UpdatedNetworkInterface) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *UpdatedNetworkInterface) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *UpdatedNetworkInterface) UnsetDescription() {
	o.Description.Unset()
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatedNetworkInterface) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId.Get()) {
		var ret string
		return ret
	}
	return *o.ProjectId.Get()
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatedNetworkInterface) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectId.Get(), o.ProjectId.IsSet()
}

// HasProjectId returns a boolean if a field has been set.
func (o *UpdatedNetworkInterface) HasProjectId() bool {
	if o != nil && o.ProjectId.IsSet() {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given NullableString and assigns it to the ProjectId field.
func (o *UpdatedNetworkInterface) SetProjectId(v string) {
	o.ProjectId.Set(&v)
}

// SetProjectIdNil sets the value for ProjectId to be an explicit nil
func (o *UpdatedNetworkInterface) SetProjectIdNil() {
	o.ProjectId.Set(nil)
}

// UnsetProjectId ensures that no value is present for ProjectId, not even an explicit nil
func (o *UpdatedNetworkInterface) UnsetProjectId() {
	o.ProjectId.Unset()
}

// GetIsNetworkInterfaceSecurityEnabled returns the IsNetworkInterfaceSecurityEnabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatedNetworkInterface) GetIsNetworkInterfaceSecurityEnabled() bool {
	if o == nil || IsNil(o.IsNetworkInterfaceSecurityEnabled.Get()) {
		var ret bool
		return ret
	}
	return *o.IsNetworkInterfaceSecurityEnabled.Get()
}

// GetIsNetworkInterfaceSecurityEnabledOk returns a tuple with the IsNetworkInterfaceSecurityEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatedNetworkInterface) GetIsNetworkInterfaceSecurityEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsNetworkInterfaceSecurityEnabled.Get(), o.IsNetworkInterfaceSecurityEnabled.IsSet()
}

// HasIsNetworkInterfaceSecurityEnabled returns a boolean if a field has been set.
func (o *UpdatedNetworkInterface) HasIsNetworkInterfaceSecurityEnabled() bool {
	if o != nil && o.IsNetworkInterfaceSecurityEnabled.IsSet() {
		return true
	}

	return false
}

// SetIsNetworkInterfaceSecurityEnabled gets a reference to the given NullableBool and assigns it to the IsNetworkInterfaceSecurityEnabled field.
func (o *UpdatedNetworkInterface) SetIsNetworkInterfaceSecurityEnabled(v bool) {
	o.IsNetworkInterfaceSecurityEnabled.Set(&v)
}

// SetIsNetworkInterfaceSecurityEnabledNil sets the value for IsNetworkInterfaceSecurityEnabled to be an explicit nil
func (o *UpdatedNetworkInterface) SetIsNetworkInterfaceSecurityEnabledNil() {
	o.IsNetworkInterfaceSecurityEnabled.Set(nil)
}

// UnsetIsNetworkInterfaceSecurityEnabled ensures that no value is present for IsNetworkInterfaceSecurityEnabled, not even an explicit nil
func (o *UpdatedNetworkInterface) UnsetIsNetworkInterfaceSecurityEnabled() {
	o.IsNetworkInterfaceSecurityEnabled.Unset()
}

// GetSecurityGroups returns the SecurityGroups field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatedNetworkInterface) GetSecurityGroups() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.SecurityGroups
}

// GetSecurityGroupsOk returns a tuple with the SecurityGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatedNetworkInterface) GetSecurityGroupsOk() ([]string, bool) {
	if o == nil || IsNil(o.SecurityGroups) {
		return nil, false
	}
	return o.SecurityGroups, true
}

// HasSecurityGroups returns a boolean if a field has been set.
func (o *UpdatedNetworkInterface) HasSecurityGroups() bool {
	if o != nil && !IsNil(o.SecurityGroups) {
		return true
	}

	return false
}

// SetSecurityGroups gets a reference to the given []string and assigns it to the SecurityGroups field.
func (o *UpdatedNetworkInterface) SetSecurityGroups(v []string) {
	o.SecurityGroups = v
}

// GetMacAddress returns the MacAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatedNetworkInterface) GetMacAddress() string {
	if o == nil || IsNil(o.MacAddress.Get()) {
		var ret string
		return ret
	}
	return *o.MacAddress.Get()
}

// GetMacAddressOk returns a tuple with the MacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatedNetworkInterface) GetMacAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MacAddress.Get(), o.MacAddress.IsSet()
}

// HasMacAddress returns a boolean if a field has been set.
func (o *UpdatedNetworkInterface) HasMacAddress() bool {
	if o != nil && o.MacAddress.IsSet() {
		return true
	}

	return false
}

// SetMacAddress gets a reference to the given NullableString and assigns it to the MacAddress field.
func (o *UpdatedNetworkInterface) SetMacAddress(v string) {
	o.MacAddress.Set(&v)
}

// SetMacAddressNil sets the value for MacAddress to be an explicit nil
func (o *UpdatedNetworkInterface) SetMacAddressNil() {
	o.MacAddress.Set(nil)
}

// UnsetMacAddress ensures that no value is present for MacAddress, not even an explicit nil
func (o *UpdatedNetworkInterface) UnsetMacAddress() {
	o.MacAddress.Unset()
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatedNetworkInterface) GetDeviceId() string {
	if o == nil || IsNil(o.DeviceId.Get()) {
		var ret string
		return ret
	}
	return *o.DeviceId.Get()
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatedNetworkInterface) GetDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeviceId.Get(), o.DeviceId.IsSet()
}

// HasDeviceId returns a boolean if a field has been set.
func (o *UpdatedNetworkInterface) HasDeviceId() bool {
	if o != nil && o.DeviceId.IsSet() {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given NullableString and assigns it to the DeviceId field.
func (o *UpdatedNetworkInterface) SetDeviceId(v string) {
	o.DeviceId.Set(&v)
}

// SetDeviceIdNil sets the value for DeviceId to be an explicit nil
func (o *UpdatedNetworkInterface) SetDeviceIdNil() {
	o.DeviceId.Set(nil)
}

// UnsetDeviceId ensures that no value is present for DeviceId, not even an explicit nil
func (o *UpdatedNetworkInterface) UnsetDeviceId() {
	o.DeviceId.Unset()
}

// GetSecondaryIps returns the SecondaryIps field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatedNetworkInterface) GetSecondaryIps() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.SecondaryIps
}

// GetSecondaryIpsOk returns a tuple with the SecondaryIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatedNetworkInterface) GetSecondaryIpsOk() ([]string, bool) {
	if o == nil || IsNil(o.SecondaryIps) {
		return nil, false
	}
	return o.SecondaryIps, true
}

// HasSecondaryIps returns a boolean if a field has been set.
func (o *UpdatedNetworkInterface) HasSecondaryIps() bool {
	if o != nil && !IsNil(o.SecondaryIps) {
		return true
	}

	return false
}

// SetSecondaryIps gets a reference to the given []string and assigns it to the SecondaryIps field.
func (o *UpdatedNetworkInterface) SetSecondaryIps(v []string) {
	o.SecondaryIps = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatedNetworkInterface) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatedNetworkInterface) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *UpdatedNetworkInterface) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableTime and assigns it to the CreatedAt field.
func (o *UpdatedNetworkInterface) SetCreatedAt(v time.Time) {
	o.CreatedAt.Set(&v)
}

// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *UpdatedNetworkInterface) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *UpdatedNetworkInterface) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatedNetworkInterface) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatedNetworkInterface) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *UpdatedNetworkInterface) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *UpdatedNetworkInterface) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}

// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *UpdatedNetworkInterface) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *UpdatedNetworkInterface) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

// GetPrivateIp returns the PrivateIp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatedNetworkInterface) GetPrivateIp() string {
	if o == nil || IsNil(o.PrivateIp.Get()) {
		var ret string
		return ret
	}
	return *o.PrivateIp.Get()
}

// GetPrivateIpOk returns a tuple with the PrivateIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatedNetworkInterface) GetPrivateIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrivateIp.Get(), o.PrivateIp.IsSet()
}

// HasPrivateIp returns a boolean if a field has been set.
func (o *UpdatedNetworkInterface) HasPrivateIp() bool {
	if o != nil && o.PrivateIp.IsSet() {
		return true
	}

	return false
}

// SetPrivateIp gets a reference to the given NullableString and assigns it to the PrivateIp field.
func (o *UpdatedNetworkInterface) SetPrivateIp(v string) {
	o.PrivateIp.Set(&v)
}

// SetPrivateIpNil sets the value for PrivateIp to be an explicit nil
func (o *UpdatedNetworkInterface) SetPrivateIpNil() {
	o.PrivateIp.Set(nil)
}

// UnsetPrivateIp ensures that no value is present for PrivateIp, not even an explicit nil
func (o *UpdatedNetworkInterface) UnsetPrivateIp() {
	o.PrivateIp.Unset()
}

func (o UpdatedNetworkInterface) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatedNetworkInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.ProjectId.IsSet() {
		toSerialize["project_id"] = o.ProjectId.Get()
	}
	if o.IsNetworkInterfaceSecurityEnabled.IsSet() {
		toSerialize["is_network_interface_security_enabled"] = o.IsNetworkInterfaceSecurityEnabled.Get()
	}
	if o.SecurityGroups != nil {
		toSerialize["security_groups"] = o.SecurityGroups
	}
	if o.MacAddress.IsSet() {
		toSerialize["mac_address"] = o.MacAddress.Get()
	}
	if o.DeviceId.IsSet() {
		toSerialize["device_id"] = o.DeviceId.Get()
	}
	if o.SecondaryIps != nil {
		toSerialize["secondary_ips"] = o.SecondaryIps
	}
	if o.CreatedAt.IsSet() {
		toSerialize["created_at"] = o.CreatedAt.Get()
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updated_at"] = o.UpdatedAt.Get()
	}
	if o.PrivateIp.IsSet() {
		toSerialize["private_ip"] = o.PrivateIp.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdatedNetworkInterface) UnmarshalJSON(data []byte) (err error) {
	varUpdatedNetworkInterface := _UpdatedNetworkInterface{}

	err = json.Unmarshal(data, &varUpdatedNetworkInterface)

	if err != nil {
		return err
	}

	*o = UpdatedNetworkInterface(varUpdatedNetworkInterface)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "status")
		delete(additionalProperties, "description")
		delete(additionalProperties, "project_id")
		delete(additionalProperties, "is_network_interface_security_enabled")
		delete(additionalProperties, "security_groups")
		delete(additionalProperties, "mac_address")
		delete(additionalProperties, "device_id")
		delete(additionalProperties, "secondary_ips")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "private_ip")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdatedNetworkInterface struct {
	value *UpdatedNetworkInterface
	isSet bool
}

func (v NullableUpdatedNetworkInterface) Get() *UpdatedNetworkInterface {
	return v.value
}

func (v *NullableUpdatedNetworkInterface) Set(val *UpdatedNetworkInterface) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatedNetworkInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatedNetworkInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatedNetworkInterface(val *UpdatedNetworkInterface) *NullableUpdatedNetworkInterface {
	return &NullableUpdatedNetworkInterface{value: val, isSet: true}
}

func (v NullableUpdatedNetworkInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatedNetworkInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
