/*
Beyond Compute Service(BCS) API

Beyond Compute Service API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bcs

import (
	"encoding/json"
	"fmt"
)

// checks if the BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel{}

// BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel struct for BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel
type BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel struct {
	PublicIp             BcsInstanceV1ApiAssociatePublicIpModelPublicIpModel `json:"public_ip"`
	AdditionalProperties map[string]interface{}
}

type _BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel

// NewBcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel instantiates a new BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel(publicIp BcsInstanceV1ApiAssociatePublicIpModelPublicIpModel) *BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel {
	this := BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel{}
	this.PublicIp = publicIp
	return &this
}

// NewBcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModelWithDefaults instantiates a new BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModelWithDefaults() *BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel {
	this := BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel{}
	return &this
}

// GetPublicIp returns the PublicIp field value
func (o *BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel) GetPublicIp() BcsInstanceV1ApiAssociatePublicIpModelPublicIpModel {
	if o == nil {
		var ret BcsInstanceV1ApiAssociatePublicIpModelPublicIpModel
		return ret
	}

	return o.PublicIp
}

// GetPublicIpOk returns a tuple with the PublicIp field value
// and a boolean to check if the value has been set.
func (o *BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel) GetPublicIpOk() (*BcsInstanceV1ApiAssociatePublicIpModelPublicIpModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicIp, true
}

// SetPublicIp sets field value
func (o *BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel) SetPublicIp(v BcsInstanceV1ApiAssociatePublicIpModelPublicIpModel) {
	o.PublicIp = v
}

func (o BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["public_ip"] = o.PublicIp

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"public_ip",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel := _BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel{}

	err = json.Unmarshal(data, &varBcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel)

	if err != nil {
		return err
	}

	*o = BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel(varBcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "public_ip")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel struct {
	value *BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel
	isSet bool
}

func (v NullableBcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel) Get() *BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel {
	return v.value
}

func (v *NullableBcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel) Set(val *BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel(val *BcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel) *NullableBcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel {
	return &NullableBcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel{value: val, isSet: true}
}

func (v NullableBcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBcsInstanceV1ApiAssociatePublicIpModelResponsePublicIpModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
