/*
Beyond Networking Service(BNS) VPC API

BNS VPC API

API version: 1.3.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vpc

import (
	"encoding/json"
	"fmt"
)

// checks if the ListSubnetSharedProjectsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListSubnetSharedProjectsResponse{}

// ListSubnetSharedProjectsResponse struct for ListSubnetSharedProjectsResponse
type ListSubnetSharedProjectsResponse struct {
	// 서브넷을 공유받은 프로젝트 목록
	Projects             []Project `json:"projects"`
	AdditionalProperties map[string]interface{}
}

type _ListSubnetSharedProjectsResponse ListSubnetSharedProjectsResponse

// NewListSubnetSharedProjectsResponse instantiates a new ListSubnetSharedProjectsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListSubnetSharedProjectsResponse(projects []Project) *ListSubnetSharedProjectsResponse {
	this := ListSubnetSharedProjectsResponse{}
	this.Projects = projects
	return &this
}

// NewListSubnetSharedProjectsResponseWithDefaults instantiates a new ListSubnetSharedProjectsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSubnetSharedProjectsResponseWithDefaults() *ListSubnetSharedProjectsResponse {
	this := ListSubnetSharedProjectsResponse{}
	return &this
}

// GetProjects returns the Projects field value
func (o *ListSubnetSharedProjectsResponse) GetProjects() []Project {
	if o == nil {
		var ret []Project
		return ret
	}

	return o.Projects
}

// GetProjectsOk returns a tuple with the Projects field value
// and a boolean to check if the value has been set.
func (o *ListSubnetSharedProjectsResponse) GetProjectsOk() ([]Project, bool) {
	if o == nil {
		return nil, false
	}
	return o.Projects, true
}

// SetProjects sets field value
func (o *ListSubnetSharedProjectsResponse) SetProjects(v []Project) {
	o.Projects = v
}

func (o ListSubnetSharedProjectsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListSubnetSharedProjectsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["projects"] = o.Projects

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListSubnetSharedProjectsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"projects",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListSubnetSharedProjectsResponse := _ListSubnetSharedProjectsResponse{}

	err = json.Unmarshal(data, &varListSubnetSharedProjectsResponse)

	if err != nil {
		return err
	}

	*o = ListSubnetSharedProjectsResponse(varListSubnetSharedProjectsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "projects")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListSubnetSharedProjectsResponse struct {
	value *ListSubnetSharedProjectsResponse
	isSet bool
}

func (v NullableListSubnetSharedProjectsResponse) Get() *ListSubnetSharedProjectsResponse {
	return v.value
}

func (v *NullableListSubnetSharedProjectsResponse) Set(val *ListSubnetSharedProjectsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListSubnetSharedProjectsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListSubnetSharedProjectsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSubnetSharedProjectsResponse(val *ListSubnetSharedProjectsResponse) *NullableListSubnetSharedProjectsResponse {
	return &NullableListSubnetSharedProjectsResponse{value: val, isSet: true}
}

func (v NullableListSubnetSharedProjectsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSubnetSharedProjectsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
