/*
KC OpenAPI Island

API configuration and service routing management for Kakao Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package config

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateClientMetadataRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateClientMetadataRequest{}

// CreateClientMetadataRequest struct for CreateClientMetadataRequest
type CreateClientMetadataRequest struct {
	Id                   string            `json:"id"`
	Upstreams            map[string]string `json:"upstreams"`
	References           map[string]string `json:"references"`
	Cors                 Cors              `json:"cors"`
	AdditionalProperties map[string]interface{}
}

type _CreateClientMetadataRequest CreateClientMetadataRequest

// NewCreateClientMetadataRequest instantiates a new CreateClientMetadataRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClientMetadataRequest(id string, upstreams map[string]string, references map[string]string, cors Cors) *CreateClientMetadataRequest {
	this := CreateClientMetadataRequest{}
	this.Id = id
	this.Upstreams = upstreams
	this.References = references
	this.Cors = cors
	return &this
}

// NewCreateClientMetadataRequestWithDefaults instantiates a new CreateClientMetadataRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClientMetadataRequestWithDefaults() *CreateClientMetadataRequest {
	this := CreateClientMetadataRequest{}
	return &this
}

// GetId returns the Id field value
func (o *CreateClientMetadataRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateClientMetadataRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateClientMetadataRequest) SetId(v string) {
	o.Id = v
}

// GetUpstreams returns the Upstreams field value
func (o *CreateClientMetadataRequest) GetUpstreams() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Upstreams
}

// GetUpstreamsOk returns a tuple with the Upstreams field value
// and a boolean to check if the value has been set.
func (o *CreateClientMetadataRequest) GetUpstreamsOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Upstreams, true
}

// SetUpstreams sets field value
func (o *CreateClientMetadataRequest) SetUpstreams(v map[string]string) {
	o.Upstreams = v
}

// GetReferences returns the References field value
func (o *CreateClientMetadataRequest) GetReferences() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.References
}

// GetReferencesOk returns a tuple with the References field value
// and a boolean to check if the value has been set.
func (o *CreateClientMetadataRequest) GetReferencesOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.References, true
}

// SetReferences sets field value
func (o *CreateClientMetadataRequest) SetReferences(v map[string]string) {
	o.References = v
}

// GetCors returns the Cors field value
func (o *CreateClientMetadataRequest) GetCors() Cors {
	if o == nil {
		var ret Cors
		return ret
	}

	return o.Cors
}

// GetCorsOk returns a tuple with the Cors field value
// and a boolean to check if the value has been set.
func (o *CreateClientMetadataRequest) GetCorsOk() (*Cors, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cors, true
}

// SetCors sets field value
func (o *CreateClientMetadataRequest) SetCors(v Cors) {
	o.Cors = v
}

func (o CreateClientMetadataRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateClientMetadataRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["upstreams"] = o.Upstreams
	toSerialize["references"] = o.References
	toSerialize["cors"] = o.Cors

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateClientMetadataRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"upstreams",
		"references",
		"cors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateClientMetadataRequest := _CreateClientMetadataRequest{}

	err = json.Unmarshal(data, &varCreateClientMetadataRequest)

	if err != nil {
		return err
	}

	*o = CreateClientMetadataRequest(varCreateClientMetadataRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "upstreams")
		delete(additionalProperties, "references")
		delete(additionalProperties, "cors")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateClientMetadataRequest struct {
	value *CreateClientMetadataRequest
	isSet bool
}

func (v NullableCreateClientMetadataRequest) Get() *CreateClientMetadataRequest {
	return v.value
}

func (v *NullableCreateClientMetadataRequest) Set(val *CreateClientMetadataRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClientMetadataRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClientMetadataRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClientMetadataRequest(val *CreateClientMetadataRequest) *NullableCreateClientMetadataRequest {
	return &NullableCreateClientMetadataRequest{value: val, isSet: true}
}

func (v NullableCreateClientMetadataRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClientMetadataRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
