/*
Beyond Compute Service(BCS) Image API

Beyond Compute Service Image API

API version: 1.3.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package image

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateImageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateImageResponse{}

// UpdateImageResponse struct for UpdateImageResponse
type UpdateImageResponse struct {
	// 수정된 이미지 정보
	Image                UpdatedImage `json:"image"`
	AdditionalProperties map[string]interface{}
}

type _UpdateImageResponse UpdateImageResponse

// NewUpdateImageResponse instantiates a new UpdateImageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateImageResponse(image UpdatedImage) *UpdateImageResponse {
	this := UpdateImageResponse{}
	this.Image = image
	return &this
}

// NewUpdateImageResponseWithDefaults instantiates a new UpdateImageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateImageResponseWithDefaults() *UpdateImageResponse {
	this := UpdateImageResponse{}
	return &this
}

// GetImage returns the Image field value
func (o *UpdateImageResponse) GetImage() UpdatedImage {
	if o == nil {
		var ret UpdatedImage
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *UpdateImageResponse) GetImageOk() (*UpdatedImage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *UpdateImageResponse) SetImage(v UpdatedImage) {
	o.Image = v
}

func (o UpdateImageResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateImageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["image"] = o.Image

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateImageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"image",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateImageResponse := _UpdateImageResponse{}

	err = json.Unmarshal(data, &varUpdateImageResponse)

	if err != nil {
		return err
	}

	*o = UpdateImageResponse(varUpdateImageResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "image")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateImageResponse struct {
	value *UpdateImageResponse
	isSet bool
}

func (v NullableUpdateImageResponse) Get() *UpdateImageResponse {
	return v.value
}

func (v *NullableUpdateImageResponse) Set(val *UpdateImageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateImageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateImageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateImageResponse(val *UpdateImageResponse) *NullableUpdateImageResponse {
	return &NullableUpdateImageResponse{value: val, isSet: true}
}

func (v NullableUpdateImageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateImageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
