/*
Beyond Compute Service(BCS) Image API

Beyond Compute Service Image API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package image

import (
	"encoding/json"
	"fmt"
)

// checks if the BcsImageV1ApiGetImageModelResponseImageModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BcsImageV1ApiGetImageModelResponseImageModel{}

// BcsImageV1ApiGetImageModelResponseImageModel struct for BcsImageV1ApiGetImageModelResponseImageModel
type BcsImageV1ApiGetImageModelResponseImageModel struct {
	Image                BcsImageV1ApiGetImageModelImageModel `json:"image"`
	AdditionalProperties map[string]interface{}
}

type _BcsImageV1ApiGetImageModelResponseImageModel BcsImageV1ApiGetImageModelResponseImageModel

// NewBcsImageV1ApiGetImageModelResponseImageModel instantiates a new BcsImageV1ApiGetImageModelResponseImageModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBcsImageV1ApiGetImageModelResponseImageModel(image BcsImageV1ApiGetImageModelImageModel) *BcsImageV1ApiGetImageModelResponseImageModel {
	this := BcsImageV1ApiGetImageModelResponseImageModel{}
	this.Image = image
	return &this
}

// NewBcsImageV1ApiGetImageModelResponseImageModelWithDefaults instantiates a new BcsImageV1ApiGetImageModelResponseImageModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBcsImageV1ApiGetImageModelResponseImageModelWithDefaults() *BcsImageV1ApiGetImageModelResponseImageModel {
	this := BcsImageV1ApiGetImageModelResponseImageModel{}
	return &this
}

// GetImage returns the Image field value
func (o *BcsImageV1ApiGetImageModelResponseImageModel) GetImage() BcsImageV1ApiGetImageModelImageModel {
	if o == nil {
		var ret BcsImageV1ApiGetImageModelImageModel
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *BcsImageV1ApiGetImageModelResponseImageModel) GetImageOk() (*BcsImageV1ApiGetImageModelImageModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *BcsImageV1ApiGetImageModelResponseImageModel) SetImage(v BcsImageV1ApiGetImageModelImageModel) {
	o.Image = v
}

func (o BcsImageV1ApiGetImageModelResponseImageModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BcsImageV1ApiGetImageModelResponseImageModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["image"] = o.Image

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BcsImageV1ApiGetImageModelResponseImageModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"image",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBcsImageV1ApiGetImageModelResponseImageModel := _BcsImageV1ApiGetImageModelResponseImageModel{}

	err = json.Unmarshal(data, &varBcsImageV1ApiGetImageModelResponseImageModel)

	if err != nil {
		return err
	}

	*o = BcsImageV1ApiGetImageModelResponseImageModel(varBcsImageV1ApiGetImageModelResponseImageModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "image")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBcsImageV1ApiGetImageModelResponseImageModel struct {
	value *BcsImageV1ApiGetImageModelResponseImageModel
	isSet bool
}

func (v NullableBcsImageV1ApiGetImageModelResponseImageModel) Get() *BcsImageV1ApiGetImageModelResponseImageModel {
	return v.value
}

func (v *NullableBcsImageV1ApiGetImageModelResponseImageModel) Set(val *BcsImageV1ApiGetImageModelResponseImageModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBcsImageV1ApiGetImageModelResponseImageModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBcsImageV1ApiGetImageModelResponseImageModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBcsImageV1ApiGetImageModelResponseImageModel(val *BcsImageV1ApiGetImageModelResponseImageModel) *NullableBcsImageV1ApiGetImageModelResponseImageModel {
	return &NullableBcsImageV1ApiGetImageModelResponseImageModel{value: val, isSet: true}
}

func (v NullableBcsImageV1ApiGetImageModelResponseImageModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBcsImageV1ApiGetImageModelResponseImageModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
