/*
Beyond Compute Service(BCS) Image API

Beyond Compute Service Image API

API version: 1.3.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package image

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateImageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateImageRequest{}

// UpdateImageRequest struct for UpdateImageRequest
type UpdateImageRequest struct {
	// 수정할 이미지 정보
	Image                UpdateImage `json:"image"`
	AdditionalProperties map[string]interface{}
}

type _UpdateImageRequest UpdateImageRequest

// NewUpdateImageRequest instantiates a new UpdateImageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateImageRequest(image UpdateImage) *UpdateImageRequest {
	this := UpdateImageRequest{}
	this.Image = image
	return &this
}

// NewUpdateImageRequestWithDefaults instantiates a new UpdateImageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateImageRequestWithDefaults() *UpdateImageRequest {
	this := UpdateImageRequest{}
	return &this
}

// GetImage returns the Image field value
func (o *UpdateImageRequest) GetImage() UpdateImage {
	if o == nil {
		var ret UpdateImage
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *UpdateImageRequest) GetImageOk() (*UpdateImage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *UpdateImageRequest) SetImage(v UpdateImage) {
	o.Image = v
}

func (o UpdateImageRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateImageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["image"] = o.Image

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateImageRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"image",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateImageRequest := _UpdateImageRequest{}

	err = json.Unmarshal(data, &varUpdateImageRequest)

	if err != nil {
		return err
	}

	*o = UpdateImageRequest(varUpdateImageRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "image")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateImageRequest struct {
	value *UpdateImageRequest
	isSet bool
}

func (v NullableUpdateImageRequest) Get() *UpdateImageRequest {
	return v.value
}

func (v *NullableUpdateImageRequest) Set(val *UpdateImageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateImageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateImageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateImageRequest(val *UpdateImageRequest) *NullableUpdateImageRequest {
	return &NullableUpdateImageRequest{value: val, isSet: true}
}

func (v NullableUpdateImageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateImageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
